### PR TITLE
bug: Fix indentation for comment at end of function followed by a comma

### LINKED ISSUE #6511: `if` with comments indentation is still broken in v3.9.5
## Bug report

This issue should have been fixed by https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6480 which fixed https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6478, but it seems it fixes only the case when there is only one comment.

### Code snippet that reproduces the problem

```
class X {
    public function save(array $data = []): self
    {
        // custom DB processing
        $hookBeforeInsertIndex = $this->onHook(self::HOOK_BEFORE_INSERT, function ($ignore, &$data) {
            if ($this->id_field !== 'id') {
                throw new \Exception('Unsupported ID field name');
            }
            // $isInsert = !$this->isLoaded();

            // logging/auditing is done solely by ... class
        }, []);
        
        // ...
    }
}
```

```diff
   2) maha-atk4/src/MyModel.php (braces)
      ---------- begin diff ----------
--- /builds/mvorisek/xxx/src/MyModel.php
+++ /builds/mvorisek/xxx/src/MyModel.php
@@ -141,9 +141,9 @@
             if ($this->id_field !== 'id') {
                 throw new \Exception('Unsupported ID field name');
             }
-            // $isInsert = !$this->isLoaded();
+        // $isInsert = !$this->isLoaded();
 
-            // logging/auditing is done solely by ... class
+        // logging/auditing is done solely by ... class
         }, []);
 
         try {
      ----------- end diff -----------
```

### PR DESCRIPTION
**Pull request by julienfalque**
Fixes #6511.

### CODE REVIEW

File: tests/Fixer/Basic/BracesFixerTest.php [hunk 1]
```diff
@@ -3029,14 +3029,7 @@ public function provideFixCommentBeforeBraceCases(): iterable
     } else {
         echo "unknown API";
         // sth
-    }
-
-    return $this->guess($class, $property, function (Constraint $constraint) use ($guesser) {
-        return $guesser->guessRequiredForConstraint($constraint);
-    // Fallback to false...
```
Comment (julienfalque) [inline tests/Fixer/Basic/BracesFixerTest.php:3036]: This is yet another case of comment that is meant for the next line and thus should be unindented. This is not reliable and we should drop this IMO. Related discussion: #6490.

Comment (jrmajor) [reply tests/Fixer/Basic/BracesFixerTest.php:3036]: #6490 is a bit different, as switch cases have no braces. This comment should just be indented with the rest of the closure body IMO. If it's meant for the next line, it should be placed before the next line, not inside another braces block:

```php
return $this->guess(
	$class,
	$property,
	function (Constraint $constraint) use ($guesser) {
		return $guesser->guessRequiredForConstraint($constraint);
	},
    // Fallback to false...
    // ... due to sth...
	false,
);
```

**Comment by keradus** [comment]
thanks @julienfalque !
