### PR TITLE
bug: Exclude `$this` from `TernaryToNullCoalescingFixer`

### LINKED ISSUE #7051: `isset($this) ? $this :` should not be transformed to `$this ??` as not equivalent
### Description

PHP-CS-Fixer suggests to replace `isset($this) ? $this : new $baseClass()` with `$this ?? new $baseClass()` but when using this code in a `Closure` and this closure is executed without bound context, the first syntax works fine while the second that CS-Fixer suggests will throw:
```
Error : Using $this when not in object context
```

### Runtime version

`3.17.0`

### Used command

```
./vendor/bin/php-cs-fixer fix -v --diff --dry-run
```

### Configuration file

```php
<?php

use PhpCsFixer\Config;
use PhpCsFixer\Finder;

return (new Config())
    ->setRules(['@PHP71Migration' => true])
    ->setFinder(
         Finder::create()
            ->in(__DIR__)
            ->path('file.php')
     )
     ->setUsingCache(true)
     ->setRiskyAllowed(true);
```

### Code snippet that reproduces the problem

**file.php**

```php
<?php

$f = function () {
    return isset($this) ? $this : 42;
};

echo $f();
```

This output `42`

Fix it with CS-Fixer (using `@PHP71Migration`)

```php
<?php

$f = function () {
    return $this ?? 42;
};

echo $f();
```

And now running it you get:
```
Fatal error: Uncaught Error: Using $this when not in object context
```

### PR DESCRIPTION
**Pull request by kylekatarnls**
Fix #7051

### CODE REVIEW

File: src/Fixer/Operator/TernaryToNullCoalescingFixer.php [hunk 1]
```diff
@@ -89,6 +89,10 @@ private function fixIsset(Tokens $tokens, int $index): void
             return; // some weird stuff inside the isset
         }
 
+        if ($issetTokens->generateCode() === '$this') {
+            return; // null coalescing operator does not with $this
```
Comment (keradus) [inline src/Fixer/Operator/TernaryToNullCoalescingFixer.php:93]: Please, could we add new tests to check introduced changes and ensure it won't be broken in the future (due to, for example, to some refactoring) ?

Comment (kylekatarnls) [reply src/Fixer/Operator/TernaryToNullCoalescingFixer.php:93]: Added.

**Comment by Wirone** [comment]
@kylekatarnls please make CI green, no one is going to do code review without it 🙂. You should run `./php-cs-fixer fix` locally to apply Fixer's CS.

File: src/Fixer/Operator/TernaryToNullCoalescingFixer.php [hunk 2]
```diff
@@ -89,6 +89,10 @@ private function fixIsset(Tokens $tokens, int $index): void
             return; // some weird stuff inside the isset
         }
 
+        if ($issetTokens->generateCode() === '$this') {
```
Comment (kylekatarnls) [inline src/Fixer/Operator/TernaryToNullCoalescingFixer.php:92]:
```suggestion
        if ('$this' === $issetTokens->generateCode()) {
```

**Comment by kylekatarnls** [comment]
I like Star Wars, but Yoda-style advantage is not worth the readability compromise for me 🤣

**Comment by SpacePossum** [comment]
nice work @kylekatarnls  :+1: 

suggestion:

```php
        // search what is inside the isset()
        $issetTokens = $this->getMeaningfulSequence($tokens, $startBraceIndex, $endBraceIndex);

        if (count($issetTokens) === 1) {
            if ($issetTokens[0]->isGivenKind(T_VARIABLE) && '$this' === strtolower($issetTokens[0]->getContent())) {
                return; // do not fix `isset($this) ? x : y` as it will break code
            }
        } elseif ($this->hasChangingContent($issetTokens)) {
            return; // some weird stuff inside the isset
        }

        // search what is inside the middle argument of ternary operator
```

and adding the test will maybe explain why my suggestion:

```php
['<?php $x = isset($THIS) ? $this : null;'],
```

**Comment by kylekatarnls** [comment]
OK for the case sensitivity. Done + test case added.

I note that the case-sensitivity is not taken into account neither for issetCode !== ternaryFirstOperand check, is it intentional that:
- `isset($var) ? $var :` becomes `$var ??` but
- `isset($var) ? $VAR :` remains unmodified?

I see you also propose to check token value rather than generated code, is it for performance reason? Because we run `$issetTokens->generateCode()` later in the function anyway and the case where it's `$this` is likely super rare so I think it's not worth the extra reading complexity. I changed the code already to save `$issetTokens->generateCode()` result in a variable so you can see more easily what I mean. WDYT?

File: src/Fixer/Operator/TernaryToNullCoalescingFixer.php [hunk 3]
```diff
@@ -89,11 +89,17 @@ private function fixIsset(Tokens $tokens, int $index): void
...
+        if ('$this' !== $issetCode) {
+            return; // null coalescing operator does not with $this
+        }
+
         // search what is inside the middle argument of ternary operator
         $ternaryColonIndex = $tokens->getNextTokenOfKind($ternaryQuestionMarkIndex, [':']);
         $ternaryFirstOperandTokens = $this->getMeaningfulSequence($tokens, $ternaryQuestionMarkIndex, $ternaryColonIndex);
 
-        if ($issetTokens->generateCode() !== $ternaryFirstOperandTokens->generateCode()) {
+        if ($issetCode !== $ternaryFirstOperandTokens->generateCode()) {
```
Comment (kylekatarnls) [inline src/Fixer/Operator/TernaryToNullCoalescingFixer.php:102]:
```suggestion
        if ($issetCode !== strtolower($ternaryFirstOperandTokens->generateCode())) {
```
Shouldn't we also be case-insensitive here?

**Comment by SpacePossum** [comment]
>OK for the case sensitivity. Done + test case added.

Thank you!

>I note that the case-sensitivity is not taken into account neither for issetCode !== ternaryFirstOperand check, is it intentional that:

It is case sensitive now and should be I think. Example

```php
<?php

$var = 2;
$VAR = 1;

$a = isset($var) ? $VAR : 1;

var_dump($a);

$a = $var ?? 1;

var_dump($a);
```
```
int(1)
int(2)
```
so changing the code would yield different results at runtime so must be avoided.

>I see you also propose to check token value rather than generated code, is it for performance reason?

Partly, but also it is more easy to understand/debug as we try to work with tokens where ever possible. However this is just a preference here of mine, so others may think different.

>and the case where it's $this is likely super rare so I think it's not worth the extra reading complexity. 

I see your point, I reason however that because it is so rare we should use as little cpu cycles as possible to detect it.

I think this PR looks good :+1:

**Review by SpacePossum — APPROVED** [review]

File: src/Fixer/Operator/TernaryToNullCoalescingFixer.php (hunk 3 above)
Comment (Wirone) [reply src/Fixer/Operator/TernaryToNullCoalescingFixer.php:102]: For the record - [here's the reasoning why not](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7052#issuecomment-1589047018).

Comment (kylekatarnls) [reply src/Fixer/Operator/TernaryToNullCoalescingFixer.php:102]: Yep, and now it will also be guaranteed to be case-sensitive by unit tests 👌

File: src/Fixer/Operator/TernaryToNullCoalescingFixer.php [hunk 4]
```diff
@@ -89,11 +89,17 @@ private function fixIsset(Tokens $tokens, int $index): void
             return; // some weird stuff inside the isset
         }
 
+        $issetCode = $issetTokens->generateCode();
+
+        if ('$this' === strtolower($issetCode)) {
```
Comment (Wirone) [inline src/Fixer/Operator/TernaryToNullCoalescingFixer.php:94]: Personally I am not sure if it should be lowercased. Look at [this example](https://3v4l.org/jOXCK):

```php
class Foo {
    public function bar(): void
    {
        var_dump($this);
        var_dump($THIS);
    }
}

(new Foo())->bar();
```

`$this` is automagically defined and available, while `$THIS` is not. It's a different variable that [can be assigned within class](https://3v4l.org/200Sn) (thanks, PHP 🙄), while [`$this` can't](https://3v4l.org/1jnqZ).

It looks like we should exclude from `ternary_to_null_coalescing` only exact `$this`.

**Review by Wirone — CHANGES_REQUESTED** [review]
I believe this requires integration test, so fixer can be run on actual code, not on tokens only. Also, we probably should cover more complex scenarios like [`isset($this->foo)`](https://3v4l.org/ibBBg9), [`isset($this['foo'])`](https://3v4l.org/PjRDI), because in those cases `$this` should be kept in `isset()` too.

File: tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php [hunk 5]
```diff
@@ -174,6 +176,18 @@ public static function provideFixCases(): iterable
...
+                '<?php $x = isset($THIS) ? $THIS : null;',
+            ],
+            [
+                '<?php $x = $this->foo ?? null;',
+                '<?php $x = isset($this->foo) ? $this->foo : null;',
+            ],
+            [
+                '<?php $x = $this["foo"] ?? null;',
+                '<?php $x = isset($this["foo"]) ? $this["foo"] : null;',
+            ],
```
[the remark this answers is not in the document]
Comment (Wirone) [reply tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php:190]: But not `$thisIsSparta`, only `$this` usage (like provided examples) 😉.

[the remark this answers is not in the document]
Comment (kylekatarnls) [reply tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php:190]: > It should check if it starts with $this rather than it's equal.

Why?? `$this->foo ?? null` works fine, only `$this ?? null` does not.

[the remark this answers is not in the document]
Comment (kylekatarnls) [reply tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php:190]: `isset($this->foo) ? $this->foo : 42` and `$this->foo ?? 42` both trigger the error `Uncaught Error: Using $this when not in object context` so both code are equivalent, then PHP-CS-Fixer can suggest to replace one by another.

But it must not suggest it for exactly `isset($this)` and nothing else because in this exact case, `isset($this)` just return `false` while `$this ??` throw the error.

[the remark this answers is not in the document]
Comment (Wirone) [reply tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php:190]: Hmmm, I was pretty sure `isset()` would verify whole chain without error, but indeed it triggers an error for `isset($this->foo)` 🤔. My fault I did not check it before. It seems like an odd behavior, because both `isset($foo->bar->baz)` or `isset($foo['bar']['baz'])` check variable's existence and then go deeper. Why `$this` is different than that 🤷‍♂️?

But it can be "solved" with [`isset($this, $this->foo)`](https://3v4l.org/sQ681) and 😆. Interesting, I [tweeted about it](https://twitter.com/_Codito_/status/1668638444786970625) 😅 .

Anyway, multi-argument `isset()` won't be converted, so that's not a problem. I'll close the discussion, sorry for the noise.

**Review by Wirone — APPROVED** [review]
I still think it's more like a bug that [`$this` works differently in `isset()`](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7052#discussion_r1228315144) than regular variables, but considering current behavior this PR looks OK.

@kubawerlos will you take a look?

File: tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php [hunk 6]
```diff
@@ -41,6 +41,8 @@ public static function provideFixCases(): iterable
             ['<?php $x = isset($a) and $a ? $a : "";'],
             ['<?php $x = "isset($a) ? $a : null";'],
             ['<?php $x = isset($a) ? $$a : null;'],
+            ['<?php $x = isset($this) ? $this : null;'],
```
Comment (kubawerlos) [inline tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php:44]: Let's wrap this case and all the others using `$this` (in any casing) with `class Foo { function bar() { /* ... */ }}`, so anyone seeing it in he future will know the context.

**Review by kubawerlos — CHANGES_REQUESTED** [review]

File: tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php (hunk 6 above)
Comment (Wirone) [reply tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php:44]: But the whole point of it is to be outside of the class 🤔. Should these cases be cloned and wrapped, or just wrapped (replaced)?

Comment (kubawerlos) [reply tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php:44]: This can be present in an application, but the last one (which is `<?php $x = isset($this["foo"]) ? $this["foo"] : null;` will always result in a fatal error, so why even bother to change it? When inside of a class it is possible to have it in an application.

Comment (kylekatarnls) [reply tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php:44]: Agree to remove those cases

File: tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php (hunk 5 above)
Comment (kylekatarnls) [inline tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php:190]:
```suggestion
```

Remove tests case that are not part of the fixed issue.

File: tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php (hunk 6 above)
Comment (Wirone) [reply tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php:44]: I agree that with current PHP behavior we can remove those cases. But personally [I consider it as a bug](https://twitter.com/_Codito_/status/1669080477452455939) 😉.

**Review by Wirone — APPROVED** [review]
PS. I've deleted @kubawerlos [duplicated comment](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7052#discussion_r1231573980) 🙂.

File: tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php (hunk 6 above)
Comment (kylekatarnls) [reply tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php:44]: Yeah, my case is that `Carbon` supports macro/mixin the Laravel way and you can call those macro statically (`Carbon::myMacro()`) or dynamically (`(new Carbon())->myMacro()`), so inside the definition of myMacro we want to make sure `$this` exists, so we bind a context to the closure.

Of course my first choice was to write (simplified version):
```php
$closure->bindTo($this ?? new Carbon());
```
Sadly triggers the exception, but then I discovered expending with `isset($this) ? $this :` works 🤷 then that's where cs-fixer suggested the change, but it was not my first choice.

It sure is inconsistent: null-coalescing could just be always equivalent to expended form.

Comment (Wirone) [reply tests/Fixer/Operator/TernaryToNullCoalescingFixerTest.php:44]: There a difference between [`isset()`](https://www.php.net/manual/en/function.isset.php) and null coallesce.

> Note: Because this is a language construct and not a function, it cannot be called using [variable functions](https://www.php.net/manual/en/functions.variable-functions.php), or [named arguments](https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments).

Because of that, `isset()` can handle non-existing variables or even whole fetch chains silently. On the other hand `??` is an operator, so you need valid (existing) left side. What I personally consider as a bug is that [`isset($notExisting->some->thing)`](https://3v4l.org/b3qUC) works, while `isset($this->some->thing)` does NOT work, even though `isset($this)` alone works.

**Review by kubawerlos — APPROVED** [review]

**Comment by Wirone** [comment]
Thank you @kylekatarnls 🍻
