### PR TITLE
fix: `no_useless_concat_operator` - do not break variable

### LINKED ISSUE #7826: `no_useless_concat_operator` rule may break code
### Description

`no_useless_concat_operator` rule may break code when variables and whitespace are mixed in a string enclosed by double colons.

### Runtime version

```
PHP CS Fixer 3.48.0 Small Changes by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.2.5
```

### Used command

```bash
$ vendor/bin/php-cs-fixer fix example.php -vvv
PHP CS Fixer 3.48.0 Small Changes by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.2.5
Loaded config default from "/test/.php-cs-fixer.dist.php".
Using cache file ".php-cs-fixer.cache".
Paths from configuration file have been overridden by paths provided as command arguments.
1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

1) example.php (no_useless_concat_operator)

Fixed 1 of 1 files in 0.006 seconds, 14.000 MB memory used
```

### Configuration file

```php
<?php

$config = new PhpCsFixer\Config();

return $config
    ->setRules([
        'no_useless_concat_operator' => true,
    ]);
```

### Code snippet that reproduces the problem

```php
<?php

$param1 = 'Hello';
$param2 = 'World!';

return "$param1" . "ooo　$param2";
```

is fixed to

```php
<?php

$param1 = 'Hello';
$param2 = 'World!';

return "$param1ooo　$param2";
```

### PR DESCRIPTION
**Pull request by tamiroh**
Fixes #7826

### CODE REVIEW

File: src/Fixer/Operator/NoUselessConcatOperatorFixer.php [hunk 1]
```diff
@@ -336,4 +348,27 @@ private function containsLinebreak(Tokens $tokens, int $startIndex, int $endInde
 
         return false;
     }
+
+    /**
+     * @param array{
```
Comment (mvorisek) [inline src/Fixer/Operator/NoUselessConcatOperatorFixer.php:353]: the type should be single line as otherwise not fully fixable

File: src/Fixer/Operator/NoUselessConcatOperatorFixer.php [hunk 2]
```diff
@@ -336,4 +348,27 @@ private function containsLinebreak(Tokens $tokens, int $startIndex, int $endInde
...
+     */
+    private function operandsCanNotBeMerged(Tokens $tokens, array $firstOperand, array $secondOperand): bool
+    {
+        // If the first operand ends with a variable and the second operand does not start with a space,
+        // the variable in the first operand may be broken by the concatenation.
+
+        // example: "$param" . "hello" -> "$paramhello"
+
+        return $tokens[$firstOperand['end'] - 1]->isGivenKind(T_VARIABLE)
+            && !str_starts_with($tokens[$secondOperand['start'] + 1]->getContent(), ' ');
```
Comment (mvorisek) [inline src/Fixer/Operator/NoUselessConcatOperatorFixer.php:372]: this is too strict - the next token content must not start with identifier char

File: src/Fixer/Operator/NoUselessConcatOperatorFixer.php (hunk 1 above)
Comment (julienfalque) [reply src/Fixer/Operator/NoUselessConcatOperatorFixer.php:353]: > […] not fully fixable

What do you mean? IMO keeping it multiline is better for readiability.

Comment (julienfalque) [reply src/Fixer/Operator/NoUselessConcatOperatorFixer.php:353]: Actually, since this type is repeated several times in this class, I'd suggest creating a custom type using `@phpstan-type`

File: tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php [hunk 3]
```diff
@@ -133,6 +133,9 @@ public static function provideFixCases(): iterable
                 $f201 = b"a".b"b";
                 $f203 = "a".B"b";
                 echo b"He drank some juice made of {$fruit}s.".b" Sliced the {$fruit}s.";
+                echo "abc $d" . "e $f";
+                echo "abc $d" . "e";
+                echo "abc $d" . \'e\';
```
Comment (julienfalque) [inline tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php:138]: Please also add cases like e.g. `"$a bcd" . "e"` → `"$a bcde"`.

**Comment by tamiroh** [comment]
Adding tests is a work in progress 🏃

File: src/Fixer/Operator/NoUselessConcatOperatorFixer.php (hunk 1 above)
Comment (tamiroh) [reply src/Fixer/Operator/NoUselessConcatOperatorFixer.php]: Fixed dd9ac1e

File: src/Fixer/Operator/NoUselessConcatOperatorFixer.php (hunk 2 above)
Comment (tamiroh) [reply src/Fixer/Operator/NoUselessConcatOperatorFixer.php]: Added tests bdd1ebc

File: tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php (hunk 3 above)
Comment (tamiroh) [reply tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php:143]: Added tests bdd1ebc

File: src/Fixer/Operator/NoUselessConcatOperatorFixer.php (hunk 2 above)
Comment (tamiroh) [reply src/Fixer/Operator/NoUselessConcatOperatorFixer.php]: ... And the logic has been changed a lot. 

It may be a little tricky, but it checks for unknown variables appearing after the operands are merged.

File: tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php [hunk 4]
```diff
@@ -136,6 +136,33 @@ public static function provideFixCases(): iterable
...
+            ',
+        ];
+
+        yield 'fix if variables would not be broken' => [
+            '<?php
+                echo "$a bcde";
+                echo "abc ${d}e";
+                echo "abc $d-efg";
+                echo "abc $d-$e";
+                echo "abc $d[$e]";
```
Comment (julienfalque) [inline tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php:155]: This particular line should not be changed, `"abc $d[$e]"` is not the same as `"abc $d" . "[$e]"`.

Note that this is also true with `"abc {$d{$e}}"` which is the same as `"abc $d[$e]"` and allowed on PHP 7.4 (invalid on PHP 8.0+).

File: tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php [hunk 5]
```diff
@@ -133,6 +133,9 @@ public static function provideFixCases(): iterable
                 $f201 = b"a".b"b";
                 $f203 = "a".B"b";
                 echo b"He drank some juice made of {$fruit}s.".b" Sliced the {$fruit}s.";
+                echo "abc $d" . "e $f";
```
[the remark this answers is not in the document]
Comment (tamiroh) [reply tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php:141]: OK, I will check.

File: tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php (hunk 4 above)
Comment (tamiroh) [reply tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php:155]: I was careless... That's right.

And furthermore, `"abc $d" . "->e"` should also not be fixed to `"abc $d->e"` 😖

File: tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php [hunk 6]
```diff
@@ -136,6 +136,20 @@ public static function provideFixCases(): iterable
...
+                echo "abc $d" . \'[3]\';
+                echo "abc $d" . "->e";
+                echo "abc $d" . \'->e\';
+                echo "abc $d" . "->$e";
+                echo "abc $d" . "?->e";
+                echo "abc $d" . "?->$e";
+                echo "abc $d" . \'?->e\';
+            ',
+        ];
+
```
Comment (tamiroh) [inline tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php:152]: Added more tests that fails currently but needs to be passed. b7e764c

Comment (tamiroh) [reply tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php:152]: @Wirone @julienfalque 
Can you think of any other further cases of code breaking due to string concatenation? 🤔

File: src/Fixer/Operator/NoUselessConcatOperatorFixer.php (hunk 2 above)
Comment (tamiroh) [reply src/Fixer/Operator/NoUselessConcatOperatorFixer.php]: ...But again, the original strict logic may be more certain. 

For example, I can list the following other codes that should not be fixed, and it is difficult for me to say for sure that there are not more than these. Hmmm.

```php
echo "abc $d" . "[$e]";
echo "abc $d" . "[3]";
echo "abc $d" . '[3]';
echo "abc $d" . "->e";
echo "abc $d" . '->e';
echo "abc $d" . "->$e";
echo "abc $d" . "?->e";
echo "abc $d" . "?->$e";
echo "abc $d" . '?->e';
```

File: tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php (hunk 6 above)
Comment (tamiroh) [reply tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php:152]: Resolved 3b0e1a6

File: src/Fixer/Operator/NoUselessConcatOperatorFixer.php (hunk 2 above)
Comment (tamiroh) [reply src/Fixer/Operator/NoUselessConcatOperatorFixer.php]: 3b0e1a6 Changed to a whitelist approach so that the fixer can fix safety and certainly

28edf77 And as pointed out, added an integration test after adjusting the priority of the existing fixer

File: tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php (hunk 5 above)
[the remark this answers is not in the document]
Comment (tamiroh) [reply tests/Fixer/Operator/NoUselessConcatOperatorFixerTest.php:155]: 28edf77 Added an integration test after adjusting the priority of the existing fixer

**Comment by tamiroh** [comment]
@Wirone @julienfalque 
Could you please review this pull request again? 🙏 
I think I've done everything I need to do.

File: src/Fixer/Operator/NoUselessConcatOperatorFixer.php [hunk 7]
```diff
@@ -336,4 +327,36 @@ private function containsLinebreak(Tokens $tokens, int $startIndex, int $endInde
...
+            return false;
+        }
+        if (!$tokens[$firstOperand['end'] - 1]->isGivenKind(T_VARIABLE)) {
+            return false;
+        }
+
+        $allowedPatternsForSecondOperand = [
+            '/^\s.*/', // e.g. " foo", ' bar', " $baz"
+            '/^-(?!\>)/', // e.g. "-foo", '-bar', "-$baz"
+        ];
```
[the remark this answers is not in the document]
Comment (Wirone) [reply src/Fixer/Operator/NoUselessConcatOperatorFixer.php:348]: We can always think about making regexes configurable, so people can fine-tune this behaviour on their side 🙂.

**Comment by Wirone** [comment]
I took a brief look on a diff, but mostly I rely on @julienfalque's review here - let's merge 👍.
