### PR TITLE
bug: Fix PhpdocVarWithoutNameFixer with Closure with $this

### LINKED ISSUE #6959: `phpdoc_var_without_name` is corrupting phpdoc type with `$this`
## Bug report

`array<string, string|array{ string|\Closure(mixed, string, $this): int|float }>|false` is valid phpdoc type and must be kept unchanged.

### Description

```
   1) ui/src/Table.php (phpdoc_var_without_name)
      ---------- begin diff ----------
--- /__w/ui/ui/src/Table.php
+++ /__w/ui/ui/src/Table.php
@@ -43,7 +43,7 @@
      * Determines a strategy on how totals will be calculated. Do not touch those fields
      * directly, instead use addTotals().
      *
-     * @var array<string, string|array{ string|\Closure(mixed, string, $this): int|float }>|false
+     * @var array<string, string|array{ string|\Closure(mixed, string,): int|float }>|false
      */
     public $totalsPlan = false;
```

### Runtime version

```
PHP CS Fixer 3.16.0 BoY42 by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.18
```

### Used command

```
vendor/bin/php-cs-fixer fix --dry-run --using-cache=no --diff --verbose
```

### Configuration file

https://github.com/atk4/ui/blob/01d39d24694e4b4f63a576d090e55e0e97aaa9e4/.php-cs-fixer.dist.php

### Code snippet that reproduces the problem

```
class Table
{
    /**
     * Determines a strategy on how totals will be calculated. Do not touch those fields
     * directly, instead use addTotals().
     *
     * @var array<string, string|array{ string|\Closure(mixed, string, $this): int|float }>|false
     */
    public $totalsPlan = false;
}
```

### PR DESCRIPTION
**Pull request by mvorisek**
fix #6959

### CODE REVIEW

**Comment by Wirone** [comment]
Sorry @mvorisek I did not have time during the weekend to review this, so it wasn't included in 3.17 release... Will look as soon as possible, but this week and upcoming I have pretty busy ([PHPers conference](https://twitter.com/_Codito_/status/1655821745926832129) 😁).

File: tests/Fixer/Phpdoc/PhpdocVarWithoutNameFixerTest.php [hunk 1]
```diff
@@ -503,6 +503,50 @@ trait StaticExample {
     public static $static = "foo";
 }',
             ],
+            'testFixClosureWithThis' => [
```
Comment (Wirone) [inline tests/Fixer/Phpdoc/PhpdocVarWithoutNameFixerTest.php:506]:
```suggestion
            'complex type with union containing callable that has `$this` in signature' => [
```
Cases' names should be descriptive and friendly for `--testdox` output.

File: src/AbstractPhpdocToTypeDeclarationFixer.php [hunk 2]
```diff
@@ -31,7 +31,7 @@
  */
 abstract class AbstractPhpdocToTypeDeclarationFixer extends AbstractFixer implements ConfigurableFixerInterface
 {
-    private const CLASS_REGEX = '/^\\\\?[a-zA-Z_\\x7f-\\xff](?:\\\\?[a-zA-Z0-9_\\x7f-\\xff]+)*$/';
+    private const CLASS_REGEX = '/^\\\\?[A-Z_a-z\x80-\xff](?:\\\\?[\dA-Z_a-z\x80-\xff]+)*$/';
```
Comment (Wirone) [inline src/AbstractPhpdocToTypeDeclarationFixer.php:34]: Please do not make changes like from `a-zA-Z0-9_` to `\dA-Z_a-z` because it's exactly the same, and since it does not provide any actual change it's unnecessary to review such diffs. Please bring back previous block in each modified regex, so we can see actual change in the diff.

```suggestion
    private const CLASS_REGEX = '/^\\\\?[a-zA-Z_\x80-\xff](?:\\\\?[a-zA-Z0-9_\x80-\xff]+)*$/';
```

File: src/Fixer/Basic/PsrAutoloadingFixer.php [hunk 3]
```diff
@@ -103,7 +103,7 @@ public function supports(\SplFileInfo $file): bool
             // ignore file with extension other than php
             ('php' !== $file->getExtension())
             // ignore file with name that cannot be a class name
-            || 0 === Preg::match('/^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*$/', $file->getBasename('.php'))
+            || 0 === Preg::match('/^(?!\d)[\dA-Z_a-z\x80-\xff]+$/', $file->getBasename('.php'))
```
Comment (Wirone) [inline src/Fixer/Basic/PsrAutoloadingFixer.php:106]: It makes no sense to me - why would you use negative lookahead for `\d` and include it later in the matching group? Looking at the comment above numbers are totally valid chars for class names.

**Review by Wirone — CHANGES_REQUESTED** [review]

File: src/Fixer/Basic/PsrAutoloadingFixer.php (hunk 3 above)
Comment (mvorisek) [reply src/Fixer/Basic/PsrAutoloadingFixer.php:106]: This should be correct, class name (identifier in general) cannot start with a number.

File: src/AbstractPhpdocToTypeDeclarationFixer.php (hunk 2 above)
Comment (mvorisek) [reply src/AbstractPhpdocToTypeDeclarationFixer.php:34]: This unifies the class regex to be ASCII ordered and consistent across the whole project. Is that ok?

File: tests/Fixer/Phpdoc/PhpdocVarWithoutNameFixerTest.php (hunk 1 above)
Comment (mvorisek) [reply tests/Fixer/Phpdoc/PhpdocVarWithoutNameFixerTest.php:506]: The name will be however inconsistent with other namings here. Is that really preferred?

Comment (Wirone) [reply tests/Fixer/Phpdoc/PhpdocVarWithoutNameFixerTest.php:506]: When reviewing file I've unfolded file content above your change and found `const are not handled by this fixer` case, that's why I commented, but you're right - most of the cases in this file has camelCase notation. I think we need to convert them anyway, so let's add new cases with proper description.

File: src/AbstractPhpdocToTypeDeclarationFixer.php (hunk 2 above)
Comment (Wirone) [reply src/AbstractPhpdocToTypeDeclarationFixer.php:34]: Personally I find previous order better and more readable, and I don't like mixing such changes - SRP works in PR scope too 😉. @kubawerlos what do you think?

Comment (Wirone) [reply src/AbstractPhpdocToTypeDeclarationFixer.php]: Regex was reverted only in 1 file, but such change was made in several files :wink:.

Comment (mvorisek) [reply src/AbstractPhpdocToTypeDeclarationFixer.php:34]: I have reverted it, previously it was inconsistent and `\x7f` was wrongly present. I will move the identifier regexes into one place in another PR later.

Comment (mvorisek) [reply src/AbstractPhpdocToTypeDeclarationFixer.php:34]: Will be improved in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7010, let's merge this PR as is.

**Comment by mvorisek** [comment]
@Wirone can you please review this PR?

File: src/AbstractPhpdocToTypeDeclarationFixer.php (hunk 2 above)
Comment (mvorisek) [reply src/AbstractPhpdocToTypeDeclarationFixer.php:34]: @Wirone can you please have a look on this PR? I can then finish #7010, it will remove these fishy chars groups completely. And there are even wrong, as they do not work with `u` modifier (fixed in #7010, not to be done in this PR).

Comment (mvorisek) [reply src/AbstractPhpdocToTypeDeclarationFixer.php]: @Wirone I have reverted all unrelated changed. Now this PR is pure fix for #6959.

**Review by kubawerlos — APPROVED** [review]
Technically these changes are fine, I wonder only if `$this` is that special. Could the type be `self` instead or that would be differently "understood" by some tools?

**Comment by Wirone** [comment]
@kubawerlos `$this` is slightly different than `self` - [the former is narrower](https://phpstan.org/writing-php-code/phpdoc-types#static-and-%24this).

**Comment by mvorisek** [comment]
@Wirone can this be merged?

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
Thanks @mvorisek 🍻
