### PR TITLE
minor: Parse callable using full phpdoc grammar

### LINKED ISSUE #7093: Regression in PHPDoc parsing since 3.19.2
### Description

After upgrading to 3.19.2 from 3.18.*, a generic `array` inside a PHPDoc breaks:

```                               
        [Exception]                            
        Unable to parse phpdoc type 'string>' 

PhpCsFixer\DocBlock\TypeExpression->parse()
        in phar:///app/vendor/php-cs-fixer/shim/php-cs-fixer.phar/src/DocBlock/TypeExpression.php at line 200
```

### Runtime version

Broken on:
```
PHP CS Fixer 3.19.2 (210dd89) Triangle by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.9
```

Working on:
```
PHP CS Fixer 3.18.0 (b123395) Triangle by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.9
```

### Used command

`vendor/bin/php-cs-fixer fix -vvv --config=.php-cs-fixer.dist.php`

### Configuration file

```
return (new Config())
	->setFinder($finder)
	->setRiskyAllowed(true)
	->setIndent("\t")
	->setRules([
		'@PhpCsFixer'    => true,
	]);
```

### Code snippet that reproduces the problem

```
/**
 * @method self                          setOrderBy(array<string, string> $by)
 */
class ListDTO
{
}
```

### PR DESCRIPTION
**Pull request by mvorisek**
fix #7093

based on https://github.com/phpstan/phpdoc-parser/blob/1.22.0/doc/grammars/type.abnf#L44 grammar

### CODE REVIEW

**Comment by mvorisek** [comment]
PR is done, there are no other places where `new TypeExpression` is created from unparsed data. A patch release should be done, see #7093.

**Comment by mvorisek** [comment]
@Wirone can you please review?

File: tests/DocBlock/TypeExpressionTest.php [hunk 1]
```diff
@@ -358,6 +370,8 @@ public static function provideParseInvalidExceptionCases(): iterable
         yield ['\' unclosed string'];
 
         yield ['\' unclosed string \\\''];
+
+        yield 'generic with no arguments' => ['f<>'];
```
Comment (Wirone) [inline tests/DocBlock/TypeExpressionTest.php:374]: What is the point of generic without arguments?

File: tests/Fixtures/Integration/misc/phpdocs-invalid.test [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+ * @method  Y|X testA(int $x)
+ * @method  X testB(int $$x)
+ * @method  Y|X testC(int $x)
+ */
+class Foo
+{
+    /** @var  (X || Y) */
+    public $v1;
+
+    /** @var  (X | Y) */
```
Comment (Wirone) [inline tests/Fixtures/Integration/misc/phpdocs-invalid.test:38]: For consistency with `@method`s above and to see if `$v2`'s types are sorted:

```suggestion
    /** @var  (Y || X) */
    public $v1;

    /** @var  (Y | X) */
```

File: tests/Fixer/Phpdoc/PhpdocTypesOrderFixerTest.php [hunk 3]
```diff
@@ -138,9 +138,19 @@ public static function provideFixWithNullFirstCases(): iterable
...
+            '@method with invalid phpdoc - simple' => [
+                '<?php /** @method null|X setOrder($$by) */',
+                '<?php /** @method X|null setOrder($$by) */',
+            ],
+            '@method with invalid phpdoc - default value is not supported' => [
                 '<?php /** @method void bar(string|null $delimiter = \',<br/>\') */',
             ],
+            '@method with invalid phpdoc - with generic' => [
+                '<?php /** @method static setOrder(array<string, string> &&$by) */',
+            ],
```
Comment (Wirone) [inline tests/Fixer/Phpdoc/PhpdocTypesOrderFixerTest.php:153]: I believe this shouldn't be part of `provideFixWithNullFirstCases()` provider, because:

- this is non-fix case
- it does not relate to "null first"

File: tests/Fixer/Phpdoc/PhpdocTypesOrderFixerTest.php [hunk 4]
```diff
@@ -138,9 +138,19 @@ public static function provideFixWithNullFirstCases(): iterable
                 '<?php /** @var Foo[]|null|Foo|Foo\Bar|Foo_Bar */',
             ],
             [
-                '<?php /** @method void bar(null|string $delimiter = \',<br/>\') */',
```
Comment (Wirone) [inline tests/Fixer/Phpdoc/PhpdocTypesOrderFixerTest.php:141]: Isn't it a breaking change? If I see it correctly, the way how `@method void bar(string|null $delimiter = \',<br/>\')` is handled has changed and `string|null` won't be sorted anymore?

File: src/DocBlock/TypeExpression.php [hunk 5]
```diff
@@ -63,13 +63,19 @@ final class TypeExpression
...
                 |
-                (?<callable> # callable syntax, e.g. `callable(string): bool`
-                    (?<callable_start>(?i)(?:callable|\\\\?Closure)(?-i)\h*\(\h*)
+                (?<callable> # callable syntax, e.g. `callable(string, int...): bool`
+                    (?<callable_start>(?&name)\h*\(\h*)
                     (?<callable_arguments>
-                        (?&types_inner)
+                        (?<callable_argument>
+                            (?<callable_argument_type>(?&types_inner))
+                            (?<callable_argument_is_reference>\h*&|)
```
Comment (Wirone) [inline src/DocBlock/TypeExpression.php:71]: - shouldn't passing by reference require identifier? I don't see [PHPStan example](https://phpstan.org/writing-php-code/phpdoc-types#callables) with `type&` only (contrary to example with variadic without identifier)
- shouldn't passing by reference be disjunctive with variadic param? I was pretty sure it would be an syntax error, but it looks like it "works" (well, [does not end with fatal error, but value is not re-assigned](https://twitter.com/_Codito_/status/1674370675639820288)).

File: tests/DocBlock/TypeExpressionTest.php (hunk 1 above)
Comment (mvorisek) [reply tests/DocBlock/TypeExpressionTest.php:374]: Exactly, no point, thus not allowed ;-)

File: tests/Fixtures/Integration/misc/phpdocs-invalid.test (hunk 2 above)
Comment (mvorisek) [reply tests/Fixtures/Integration/misc/phpdocs-invalid.test:38]: This is a test for invalid phpdoc. `X | Y` is valid, `X || Y` is invalid.

File: tests/Fixer/Phpdoc/PhpdocTypesOrderFixerTest.php (hunk 4 above)
Comment (mvorisek) [reply tests/Fixer/Phpdoc/PhpdocTypesOrderFixerTest.php:141]: see https://psalm.dev/docs/annotating_code/type_syntax/callable_types/ grammar (or phpstan grammar)

`$arg=` (or `$arg =`) represents optional parameter, `$arg = const` is not valid phpdoc

File: src/DocBlock/TypeExpression.php (hunk 5 above)
Comment (mvorisek) [reply src/DocBlock/TypeExpression.php:71]: In parser we are not required to "not-match any invalid" edge usecase, we are required to "match all valid" usecases.

I coded it based on phpstan parser grammar.

To your bullet points - can you please provided phpstan and psalm online repro links, so we can see how the static analysers really understand it (or emit warnigs).

File: tests/Fixer/Phpdoc/PhpdocTypesOrderFixerTest.php (hunk 3 above)
Comment (mvorisek) [reply tests/Fixer/Phpdoc/PhpdocTypesOrderFixerTest.php]: done, `tests\Fixtures\Integration\misc\phpdocs-invalid.test` test is enought and stronger

File: tests/Fixer/Phpdoc/PhpdocTypesOrderFixerTest.php (hunk 4 above)
Comment (mvorisek) [reply tests/Fixer/Phpdoc/PhpdocTypesOrderFixerTest.php:141]: `'@method with invalid 2nd phpdoc'` testcase tests the original phpdoc will be kept as-is correctly

File: tests/Fixtures/Integration/misc/phpdocs-invalid.test (hunk 2 above)
Comment (Wirone) [reply tests/Fixtures/Integration/misc/phpdocs-invalid.test:38]: I know, but it does not change my point - there's `@method  Y|X testA(int $x)` above which is sorted (expected output has `@method X|Y testA(int $x)`. Shouldn't `@var  (Y | X)` be sorted the same way, hence proposed inverted order in the input?

Comment (mvorisek) [reply tests/Fixtures/Integration/misc/phpdocs-invalid.test]: The test is primary there to assert invalid phpdocs stay as is and fixer can finish, but I have improved the test 👍

**Review by kubawerlos — APPROVED** [review]

**Comment by Wirone** [comment]
Thank you @mvorisek 🍻
