### PR TITLE
bug: SelfStaticAccessor - fix static access inside enums

### LINKED ISSUE #7005: SelfStaticAccessorFixer - Does not fix enums
### Description
`SelfStaticAccessorFixer` does not fix usage of `static` in enums.

### Runtime version
PHP8.3 nightly, but effects all PHP versions supporting enums (8.1 and up)

### Used command

> $ sudo docker-compose run --rm --user "$(id --user):$(id --group)" php-x php php-cs-fixer fix test.php --dry-run -vvv --diff --rules=self_static_accessor

### Configuration file

None

### Code snippet that reproduces the problem

  ```php
<?php
enum Foo
{
    public const A = 123;

    public static function bar(): void
    {
        echo static::A; // expected to be fixed to `echo self::A; `
    }
}

Foo::bar();
 ```

The rationale is that since enums cannot by design be extended (nor inherit for that matter) there is never a use-case for LSB so no use-case for using `static::` inside a enum. 

ref.: https://php.watch/versions/8.1/enums#enum-inheritance

### PR DESCRIPTION
**Pull request by paulbalandan**
Fixes #7005

### CODE REVIEW

File: src/Fixer/ClassNotation/SelfStaticAccessorFixer.php [hunk 1]
```diff
@@ -29,7 +31,7 @@ final class SelfStaticAccessorFixer extends AbstractFixer
     public function getDefinition(): FixerDefinitionInterface
     {
         return new FixerDefinition(
-            'Inside a `final` class or anonymous class `self` should be preferred to `static`.',
+            'Inside a `final` class, anonymous class, or enums, `self` should be preferred over `static`.',
```
Comment (Wirone) [inline src/Fixer/ClassNotation/SelfStaticAccessorFixer.php:34]: Maybe like this? With so many commas it looks somehow wrong.

```suggestion
            'Inside an enum or `final`/anonymous class `self` should be preferred over `static`.',
```

**Review by Wirone — CHANGES_REQUESTED** [review]
Looks good! 

@paulbalandan if it's not a problem for you, can you please apply @kubawerlos' approach in the future, and provide only failing test cases in the first commit, run CI and then provide fix? Of course only for bug fixes 🙂. This way we can be sure bug was actually there and code changes fix it. When everything is provided at once, it's not that obvious if it was failing before code changes and it require manual work to verify it. Thanks in advance.

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
Thanks @paulbalandan 🍻
