### PR TITLE
fix: Look up for PHPDoc's variable name by only chars allowed in the variables

### LINKED ISSUE #7294: Two passes needed for no_superfluous_phpdoc_tags + phpdoc_add_missing_param_annotation
### Description

Two passes may be required if we use both `NoSuperfluousPhpdocTagsFixer` and `PhpdocAddMissingParamAnnotationFixer`.

### Runtime version

```
PHP CS Fixer 3.26.1 Crank Cake by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 7.4.33
```

### Configuration file

```php
<?php

$config = new PhpCsFixer\Config();

return $config
    ->setRules([
        'phpdoc_add_missing_param_annotation' => true
        'no_superfluous_phpdoc_tags' => true,
    ])
    ->setFinder(PhpCsFixer\Finder::create()
        ->in(__DIR__)
    )
;
```

### Code snippet that reproduces the problem

Let's assume we have this file:

```php
<?php

/**
 * @param int $bar Bar description
 * @param resource|null $baz=null Wrong baz description
 */
function foo($bar, $baz = null)
{
}
```

At the first pass, `NoSuperfluousPhpdocTagsFixer` changes it to

```php
<?php

/**
 * @param int $bar Bar description
 */
function foo($bar, $baz = null)
{
}
```

At the second pass, `PhpdocAddMissingParamAnnotationFixer` changes it to

```php
<?php

/**
 * @param int $bar Bar description
 * @param null|mixed $baz
 */
function foo($bar, $baz = null)
{
}
```

### PR DESCRIPTION
**Pull request by Wirone**
Fixes #7294 not by enforcing proper fixers' priorities, but by providing fix for how `@param`'s variable name is determined. PHPDoc params with descriptions are not considered as superfluous, but in order to do that, we need to determine variable name properly. Since `=` is not a char allowed in the variable name, it shouldn't be taken into consideration as a part of variable name when PHPDoc's line is parsed.

### CODE REVIEW

File: src/DocBlock/Annotation.php [hunk 1]
```diff
@@ -178,7 +178,7 @@ public function getTypeExpression(): ?TypeExpression
     public function getVariableName()
     {
         $type = preg_quote($this->getTypesContent() ?? '', '/');
-        $regex = "/@{$this->tag->getName()}\\s+({$type}\\s*)?(&\\s*)?(\\.{3}\\s*)?(?<variable>\\$.+?)(?:[\\s*]|$)/";
+        $regex = "/@{$this->tag->getName()}\\s+({$type}\\s*)?(&\\s*)?(\\.{3}\\s*)?(?<variable>\\$[a-zA-Z_]+[a-zA-Z0-9_]*)(?:.*|$)/";
```
Comment (mvorisek) [inline src/DocBlock/Annotation.php:181]: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.58.1/src/DocBlock/TypeExpression.php#L34 should be used instead

**Review by kubawerlos — APPROVED** [review]
