### PR TITLE
fix: `PhpdocToCommentFixer` on property hooks

### LINKED ISSUE #9120: `phpdoc_to_comment` trigger at phpdoc for hooks
### Problem description

Rule `phpdoc_to_comment` converts valid phpdoc on hooks to comments.

Image

### Minimal reproducer CLI command

php php-cs-fixer.phar fix /path/to/dir --rules=phpdoc_to_comment

### Minimal reproducer code snippet

public array $konzessionen {
        get => $this->konzessionen;

        /**
         * @param array<string> $value
         * @return void
         */
        set (array $value) {
            $this->konzessionen = is_array($value) ? $value : $value;
        }
    }

### Fixer version

3.88.2

### PHP version

8.4.12

### How do you run Fixer?

Composer package

### Contribution Checks

- [x] I have verified if this problem was already reported
- [x] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

### PR DESCRIPTION
**Pull request by Kinqdos**
Fixes that phpdocs gets converted to comments on property hooks. 
Fixes #9120

### CODE REVIEW

**Comment by carl-sauter** [comment]
Property hooks has no parser tokens, so I had to check for T_STRING and content. I don't know if there is a better solution for this.

File: tests/Fixer/Phpdoc/PhpdocToCommentFixerTest.php [hunk 1]
```diff
@@ -979,5 +979,21 @@ public static function provideFix84Cases(): iterable
                 }
                 PHP,
         ];
+
+        yield 'property hooks' => [
```
Comment (kubawerlos) [inline tests/Fixer/Phpdoc/PhpdocToCommentFixerTest.php:983]: Please add a test case with `GET` or `GET` as hook, sadly this is also valid code.

Comment (carl-sauter) [reply tests/Fixer/Phpdoc/PhpdocToCommentFixerTest.php:983]: You mean different casing? Wasn't sure if another rule would normalize this first

Comment (carl-sauter) [reply tests/Fixer/Phpdoc/PhpdocToCommentFixerTest.php:983]: In addition `gEt`, `GeT` or `gET` is also valid. Should be fine now

Comment (kubawerlos) [reply tests/Fixer/Phpdoc/PhpdocToCommentFixerTest.php:983]: > You mean different casing?

Yeah, I meant anything that would require using `strtolower`.

**Comment by kubawerlos** [comment]
> I don't know if there is a better solution for this.

If there is, anyone can always refactor to it.

Thank you @Kinqdos
