### PR TITLE
fix(YieldFromArrayToYieldsFixer): mark as Risky

### LINKED ISSUE #7271: `YieldFromArrayToYieldsFixer` makes non-equivalent changes
## Bug report

Consider this code:

```php
function a(): iterable {
    yield from ['a', 'b', 'c'];
    yield from ['d', 'e', 'f'];
};
```

YieldFromArrayToYieldsFixer changes this to:

```php
function a(): iterable {
    yield 'a';
    yield 'b';
    yield 'c';
    yield 'd';
    yield 'e';
    yield 'f';
};
```

In my opinion this change is reasonable. However it is not equivalent as you can see here: https://3v4l.org/OiitA

As such the fixer should be moved from `PhpCsFixerSet` into `PhpCsFixerRiskySet`.

### PR DESCRIPTION
**Pull request by keradus**
Closes #7271

### CODE REVIEW

**Comment by keradus** [comment]
cc @enumag

**Comment by enumag** [comment]
I'm honestly a lot more concerned about #7270 but still thanks for fixing this. :)

**Comment by keradus** [comment]
for #7270 look at #7273

File: src/Fixer/ArrayNotation/YieldFromArrayToYieldsFixer.php [hunk 1]
```diff
@@ -31,18 +31,26 @@ public function getDefinition(): FixerDefinitionInterface
...
         2,
         3,
     ];
 }
-')],
-            'The conversion will make the array in `yield from` changed in arrays of 1 less dimension.'
+'),
+            ],
+            'The conversion will make the array in `yield from` changed in arrays of 1 less dimension.',
+            'The rule is risky in case of `yield from` being used multiple times within single function scope and one relies on the list-alike indices (e.g. `function foo() { yield from ["a"]; yield from ["b"]; }`).'
```
Comment (Wirone) [inline src/Fixer/ArrayNotation/YieldFromArrayToYieldsFixer.php:45]: What's the context of "one relies"? One of multiple yields mentioned before? Personally I would focus on key consuming, like:

```suggestion
            'The rule is risky in case of `yield from` being used multiple times within single function scope, while using list-alike data sources (e.g. `function foo() { yield from ["a"]; yield from ["b"]; }`). It only matters when consuming such iterator with key-value context, because set of yielded keys may be changed after applying this rule.'
```

**Review by Wirone — CHANGES_REQUESTED** [review]

File: src/Fixer/ArrayNotation/YieldFromArrayToYieldsFixer.php (hunk 1 above)
Comment (keradus) [reply src/Fixer/ArrayNotation/YieldFromArrayToYieldsFixer.php:45]: by "one relies on sth" I meant "someone depends on sth".

I like your descr more, thanks

**Review by Wirone — APPROVED** [review]
