### PR TITLE
fix: Support shebang in fixers operating on PHP opening tag

### LINKED ISSUE #7634: Rule `declare_strict_types` does not work on files that start with a "hashbang" line
### Description

The rule `declare_strict_types` does not work on files that start with a "hashbang" line:

```
#!/usr/bin/env php
<?php
// the rest of the file
```

I discovered the bug when I tried to reformat a `bin/console` file generated by Symfony CLI,
but further testing soon revealed that the rule simply ignores "mixed content" files
that contain any non-PHP lines before the `<php` opening tag.

While I understand that the behaviour might be intentional (to avoid corrupting files
where the `declare` statement would have no effect or wrong effect), I also think that
the hashbang line should be an exception and files that start with it but contain no other
non-PHP content should be treated as "pure PHP" files and modified by the rule.

### Runtime version

```
PHP CS Fixer 3.43.0 Three Keys by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.3.1
```

### Used command

`vendor/bin/php-cs-fixer -vvv fix`

### Configuration file

```php
<?php
$rules = [
    'declare_strict_types' => true,
];

$finder = new PhpCsFixer\Finder();
$finder->in(__DIR__);

$config = new PhpCsFixer\Config();
$config->setRiskyAllowed(true);
$config->setRules($rules);
$config->setFinder($finder);

return $config;
```

### Code snippet that reproduces the problem

```php
#!/usr/bin/env php
<?php
echo 'PHP-CS-Fixer should add declare statement above!';
```

Expected result:

```php
#!/usr/bin/env php
<?php declare(strict_types=1);
echo 'PHP-CS-Fixer should add declare statement above!';
```

Actual result: file is not changed at all.

Here is a simple repository that demonstrates the bug:
<https://github.com/krzysztof-sikorski/php-cs-fixer-declare-strict-types-bug>

Just pull the code, execute `composer install`, and then `vendor/bin/php-cs-fixer -vvv fix`.

### PR DESCRIPTION
**Pull request by mvorisek**
fix #7634 (and #7681 duplicate)

### CODE REVIEW

File: src/Fixer/Strict/DeclareStrictTypesFixer.php [hunk 1]
```diff
@@ -53,7 +53,7 @@ public function getPriority(): int
 
     public function isCandidate(Tokens $tokens): bool
     {
-        return isset($tokens[0]) && $tokens[0]->isGivenKind(T_OPEN_TAG);
+        return null !== $this->getOpenTagIndex($tokens);
```
Comment (keradus) [inline src/Fixer/Strict/DeclareStrictTypesFixer.php:56]: would it work if we use `Tokens::isMonolithicPhp()` here instead?

Comment (mvorisek) [reply src/Fixer/Strict/DeclareStrictTypesFixer.php]: It can be used, done.

File: tests/Fixer/PhpTag/NoClosingTagFixerTest.php [hunk 2]
```diff
@@ -174,14 +174,5 @@ public static function provideWithShortOpenTagCases(): iterable
...
         ];
-
-        yield [
-            '<?= "somestring"; ?> <?= "anotherstring"; ?>',
-        ];
-
-        yield [
-            '<?= 1;',
-            '<?= 1; ?>',
-        ];
```
Comment (Wirone) [inline tests/Fixer/PhpTag/NoClosingTagFixerTest.php:185]: These test cases look like proper ones 🤔.

File: tests/Tokenizer/TokensTest.php [hunk 3]
```diff
@@ -436,9 +436,9 @@ public static function provideMonolithicPhpDetectionCases(): iterable
         yield [false, "<?=' '\n?><?\n"];
 
         // short open tag echo
-        yield [true, "<?=' ';\n"];
+        yield [false, "<?=' ';\n"];
 
-        yield [true, "<?=' '?>"];
+        yield [false, "<?=' '?>"];
```
Comment (Wirone) [inline tests/Tokenizer/TokensTest.php:441]: Why these cases have been changed? Both look like a monolithic PHP (`<?php echo ' ';` with trailing new line, `<?php echo ' '; ?>`). In general such changes should be considered as BC break.

**Review by Wirone — COMMENTED** [review]
I did not review changes in the actual fixer, I'll continue after concerns related to tests are resolved.

PS. I prefer explicit `with` / `without` instead of `/w` / `/wo` in test cases' names, but it's not something I will fight for 😉.

File: tests/Tokenizer/TokensTest.php (hunk 3 above)
Comment (mvorisek) [reply tests/Tokenizer/TokensTest.php:441]: In almost all fixers the `Tokens::isMonolithicPhp()` was/is further checked with `T_OPEN_TAG` only, ie. without `T_OPEN_TAG_WITH_ECHO`. I belive this change is thus good unification and I do not expect any CI to be broken - we no longer fix exotic `T_OPEN_TAG_WITH_ECHO`, thus fixes code before will be kept green in CI.

File: tests/Fixer/PhpTag/NoClosingTagFixerTest.php (hunk 2 above)
Comment (mvorisek) [reply tests/Fixer/PhpTag/NoClosingTagFixerTest.php:185]: related with https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7687#discussion_r1445117767 unification, see all other fixers code for more global overview

File: tests/Tokenizer/TokensTest.php (hunk 3 above)
Comment (Wirone) [reply tests/Tokenizer/TokensTest.php:441]: FYI: recently there was a [fix for short echo syntax](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7637), so yeah, even if there are not many fixers that handle this, I believe we should not change the contract just like that. Maybe you shouldn't touch more fixers than `declare_strict_types` 🤔?

**Comment by mvorisek** [comment]
I relanded the original behaviour. I do not however see any benefit by considering T_OPEN_TAG_WITH_ECHO as monotonic (one script file) as most of the fixers does not support it. Maybe they miss the support. IDK.

File: src/Fixer/Comment/HeaderCommentFixer.php [hunk 4]
```diff
@@ -112,7 +112,14 @@ public function getDefinition(): FixerDefinitionInterface
...
     {
-        return $tokens->isMonolithicPhp();
+        if ($tokens->isMonolithicPhp()) {
+            $openTagIndex = $tokens[0]->isGivenKind(T_INLINE_HTML) && $tokens->count() > 1 ? 1 : 0;
+            if (!$tokens[$openTagIndex]->isGivenKind(T_OPEN_TAG_WITH_ECHO)) {
+                return true;
+            }
+        }
+
+        return false;
```
Comment (Wirone) [inline src/Fixer/Comment/HeaderCommentFixer.php:122]: In each fixer modified in this PR it can be just:

```suggestion
        return $tokens->isMonolithicPhp() && $tokens->isTokenKindFound(T_OPEN_TAG);
```

Since `isMonolithicPhp()` already checks if there is open tag **OR** short echo tag, we can just narrow it to `T_OPEN_TAG` and it works as expected.

File: src/Fixer/PhpTag/BlankLineAfterOpeningTagFixer.php [hunk 5]
```diff
@@ -48,23 +48,23 @@ public function getPriority(): int
...
     {
-        return $tokens->isTokenKindFound(T_OPEN_TAG);
+        if ($tokens->isMonolithicPhp()) {
+            $openTagIndex = $tokens[0]->isGivenKind(T_INLINE_HTML) && $tokens->count() > 1 ? 1 : 0;
+            if (!$tokens[$openTagIndex]->isGivenKind(T_OPEN_TAG_WITH_ECHO)) {
+                return true;
+            }
+        }
+
+        return false;
```
Comment (Wirone) [inline src/Fixer/PhpTag/BlankLineAfterOpeningTagFixer.php:58]:
```suggestion
        return $tokens->isMonolithicPhp() && $tokens->isTokenKindFound(T_OPEN_TAG);
```

File: src/Fixer/PhpTag/LinebreakAfterOpeningTagFixer.php [hunk 6]
```diff
@@ -37,24 +37,28 @@ public function getDefinition(): FixerDefinitionInterface
...
     {
-        return $tokens->isTokenKindFound(T_OPEN_TAG);
+        if ($tokens->isMonolithicPhp()) {
+            $openTagIndex = $tokens[0]->isGivenKind(T_INLINE_HTML) && $tokens->count() > 1 ? 1 : 0;
+            if (!$tokens[$openTagIndex]->isGivenKind(T_OPEN_TAG_WITH_ECHO)) {
+                return true;
+            }
+        }
+
+        return false;
```
Comment (Wirone) [inline src/Fixer/PhpTag/LinebreakAfterOpeningTagFixer.php:47]:
```suggestion
        return $tokens->isMonolithicPhp() && $tokens->isTokenKindFound(T_OPEN_TAG);
```

File: src/Fixer/Strict/DeclareStrictTypesFixer.php [hunk 7]
```diff
@@ -53,7 +53,14 @@ public function getPriority(): int
...
     {
-        return isset($tokens[0]) && $tokens[0]->isGivenKind(T_OPEN_TAG);
+        if ($tokens->isMonolithicPhp()) {
+            $openTagIndex = $tokens[0]->isGivenKind(T_INLINE_HTML) && $tokens->count() > 1 ? 1 : 0;
+            if (!$tokens[$openTagIndex]->isGivenKind(T_OPEN_TAG_WITH_ECHO)) {
+                return true;
+            }
+        }
+
+        return false;
```
Comment (Wirone) [inline src/Fixer/Strict/DeclareStrictTypesFixer.php:63]:
```suggestion
        return $tokens->isMonolithicPhp() && $tokens->isTokenKindFound(T_OPEN_TAG);
```

**Review by Wirone — CHANGES_REQUESTED** [review]
Not complete review, but feedback for "ugly" changes 😉.

File: src/Fixer/Comment/HeaderCommentFixer.php (hunk 4 above)
Comment (mvorisek) [reply src/Fixer/Comment/HeaderCommentFixer.php]: Very helpful review 👍

**Comment by mvorisek** [comment]
Can this PR be merged, please?

**Comment by mvorisek** [comment]
@Wirone is there any feedback left?

**Comment by Wirone** [comment]
@mvorisek I don't know, I did not have time to look at it yet 🤷‍♂️.

**Comment by mvorisek** [comment]
Kindly ping @Wirone, the current master/release is broken.

File: src/Tokenizer/Tokens.php [hunk 8]
```diff
@@ -1127,19 +1127,21 @@ public function clearRange(int $indexStart, int $indexEnd): void
...
+                return Preg::match('/^#!.+$/', $this[0]->getContent());
+            }
 
-        if (1 === $this->countTokenKind(T_INLINE_HTML)) {
-            return Preg::match('/^#!.+$/', $this[0]->getContent());
+            return true;
         }
 
-        return 1 === ($this->countTokenKind(T_OPEN_TAG) + $this->countTokenKind(T_OPEN_TAG_WITH_ECHO));
+        return false;
```
Comment (julienfalque) [inline src/Tokenizer/Tokens.php:1144]: Why do you rewrite this method? The behavior seems to be the same but in my opinion previous version was easier to read.

File: src/Fixer/PhpTag/BlankLineAfterOpeningTagFixer.php [hunk 9]
```diff
@@ -76,17 +69,18 @@ protected function applyFix(\SplFileInfo $file, Tokens $tokens): void
...
 
-        if (!str_contains($tokens[1]->getContent(), "\n")) {
-            if ($tokens[1]->isWhitespace()) {
-                $tokens[1] = new Token([T_WHITESPACE, $lineEnding.$tokens[1]->getContent()]);
+        if (isset($tokens[$openTagIndex + 1]) && !str_contains($tokens[$openTagIndex + 1]->getContent(), "\n")) {
+            if ($tokens[$openTagIndex + 1]->isWhitespace()) {
+                $tokens[$openTagIndex + 1] = new Token([T_WHITESPACE, $lineEnding.$tokens[$openTagIndex + 1]->getContent()]);
             } else {
-                $tokens->insertAt(1, new Token([T_WHITESPACE, $lineEnding]));
+                $tokens->insertAt($openTagIndex + 1, new Token([T_WHITESPACE, $lineEnding]));
```
Comment (julienfalque) [inline src/Fixer/PhpTag/BlankLineAfterOpeningTagFixer.php:83]: Maybe we can introduce a variable like e.g. `$newLineIndex` to avoid repeating `$openTagIndex + 1`.

**Review by julienfalque — COMMENTED** [review]
Looks pretty good overall 👍

Maybe the title of the PR should be updated as the scope of changes is not limited to `declare_strict_types`

File: src/Fixer/PhpTag/BlankLineAfterOpeningTagFixer.php (hunk 9 above)
Comment (mvorisek) [reply src/Fixer/PhpTag/BlankLineAfterOpeningTagFixer.php]: why not, landed

**Comment by mvorisek** [comment]
@julienfalque review comments should be addressed as well the PR title.

**Review by Wirone — APPROVED** [review]

**Review by julienfalque — APPROVED** [review]

**Comment by Wirone** [comment]
Thanks @mvorisek 🍻

**Comment by krzysztof-sikorski** [comment]
Thank you @mvorisek 🎉
