### PR TITLE
bug: Restructure PER-CS rule sets

### LINKED ISSUE #6700: PER ruleset is misnamed
It's unfortunately a common confusion, but calling the latest ruleset "PER" is confusing and misleading.  PER stands for "PHP Evolving Recommendation".  And, there will be several of them.  What this ruleset follows is the Coding Style PER, which we've been commonly abbreviating "PER-CS".  It would be like referring to the older guidelines as "PSR", which (although people did it) is equally wrong.

It would be helpful if this project would use the proper name to minimize confusion in the future.  (Possibly with PER as an deprecated alias for it to avoid a BC break.)

### PR DESCRIPTION
**Pull request by Crell**
Resolves #6700.

This PR does a few things:

1. Sets the plan to have pinned versions of PER-CS as it evolves.  Right now there's just `PERCS10` (1.0), but as PER-CS 2.0 is now out, that can be added in a follow-up.
2. Introduces `PERCS` as a ruleset that just aliases to the latest release.  So when `PERCS20` is added, `PERCS` changes to point to that.
3. Makes `PER` an alias to `PERCS` for BC.  It can probably be deprecated and removed eventually, but I leave that to the maintainers to decide.

I don't know if there's any defaults elsewhere that should also be updated.  Again, I defer to the maintainers.

### CODE REVIEW

File: src/RuleSet/Sets/PERCS10Set.php [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+use PhpCsFixer\RuleSet\AbstractRuleSetDescription;
+
+/**
+ * @internal
+ *
+ * PER Coding Style v1.0.0.
+ *
+ * @link https://github.com/php-fig/per-coding-style/blob/1.0.0/spec.md
+ */
+final class PERCS10Set extends AbstractRuleSetDescription
```
Comment (julienfalque) [inline src/RuleSet/Sets/PERCS10Set.php:26]: I think the name is confusing: is it PER CS 1.0 ou 10? I would override `getName()` to remove the ambiguity.

File: src/RuleSet/Sets/PERCS10Set.php [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+ */
+
+namespace PhpCsFixer\RuleSet\Sets;
+
+use PhpCsFixer\RuleSet\AbstractRuleSetDescription;
+
+/**
+ * @internal
+ *
+ * PER Coding Style v1.0.0.
```
Comment (julienfalque) [inline src/RuleSet/Sets/PERCS10Set.php:22]: Would a patch version of the recommendation require a new ruleset?

File: src/RuleSet/Sets/PERSet.php [hunk 3]
```diff
@@ -26,12 +26,12 @@ final class PERSet extends AbstractRuleSetDescription
...
         return [
-            '@PSR12' => true,
+            '@PERCS' => true,
         ];
     }
 
     public function getDescription(): string
     {
-        return 'Rules that follow `PER Coding Style <https://www.php-fig.org/per/coding-style/>`_.';
+        return 'Alias for the PERCS rules.  It is recommended you use @PERCS instead.';
```
Comment (julienfalque) [inline src/RuleSet/Sets/PERSet.php:35]: Extra space:
```suggestion
        return 'Alias for the PERCS rules. It is recommended you use @PERCS instead.';
```

File: src/RuleSet/Sets/PERCS10Set.php [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+    public function getRules(): array
+    {
+        return [
+            '@PSR12' => true,
+        ];
+    }
+
+    public function getDescription(): string
+    {
+        return 'Rules that follow `PER Coding Style 1.0 <https://www.php-fig.org/per/coding-style/>`_.';
```
Comment (julienfalque) [inline src/RuleSet/Sets/PERCS10Set.php:37]: Not sure this method is always called in a reStructuredText context. But since this is quite legible, maybe that's ok anyway.

File: src/RuleSet/Sets/PERCS10Set.php (hunk 2 above)
Comment (Crell) [reply src/RuleSet/Sets/PERCS10Set.php:22]: Presumably not.  Dropping the .z here makes sense, I think.

File: src/RuleSet/Sets/PERSet.php (hunk 3 above)
Comment (Crell) [reply src/RuleSet/Sets/PERSet.php:35]: 2spaces4eva.

File: src/RuleSet/Sets/PERCS10Set.php (hunk 4 above)
Comment (Crell) [reply src/RuleSet/Sets/PERCS10Set.php:37]: No idea.  That's how the existing `PERSet` was written, so I just copied-and-modified it.  Happy to change it to whatever.

**Comment by Crell** [comment]
I've updated the names.  Let me know if I did it right or if there's some other format I should use there.  I wasn't clear if spaces were allowed.

I also realized I missed the "risky" sets before, so I added those as well.

**Comment by Crell** [comment]
Hm.  Did I not use the names correctly?  Please advise.

File: src/RuleSet/Sets/PERCSSet.php [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+ *
+ * This Ruleset always points to the latest version of PER-CS.
+ * To fix on a specific version of PER-CS, use `PERCS10` (the 1.0 release),
+ * `PERCS11` (the 1.1 release), etc.
+ */
+final class PERCSSet extends AbstractRuleSetDescription
+{
+    public function getName(): string
+    {
+        return 'PER-CS';
```
Comment (kubawerlos) [inline src/RuleSet/Sets/PERCSSet.php:32]:
```suggestion
        return '@PER-CS';
```

> Hm. Did I not use the names correctly? Please advise.

@Crell  like this?

File: src/RuleSet/Sets/PERCS10Set.php (hunk 4 above)
Comment (julienfalque) [reply src/RuleSet/Sets/PERCS10Set.php:42]: Right, let's keep it.

File: src/RuleSet/Sets/PERCSSet.php (hunk 5 above)
Comment (Crell) [reply src/RuleSet/Sets/PERCSSet.php]: Let's see if the bot likes it.

**Comment by Crell** [comment]
OK, I don't understand what the tests are objecting to now.  Can someone help me out here?  I'm confused as to what I'm still screwing up. :smile:

**Comment by kubawerlos** [comment]
Isn't the name of the test - `testFixerDocumentationFileIsUpToDate` - helping? Have you read https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/CONTRIBUTING.md? My bet would be you haven't run `php dev-tools/doc.php`.

BTW it is not illegal to run tests locally 😉

File: src/RuleSet/Sets/PERCS10RiskySet.php [hunk 6]
```diff
@@ -0,0 +1,44 @@
...
+/**
+ * @internal
+ *
+ * PER Coding Style v1.0.
+ *
+ * @link https://github.com/php-fig/per-coding-style/blob/1.0.0/spec.md
+ */
+final class PERCS10RiskySet extends AbstractRuleSetDescription
+{
+    public function getName(): string
```
Comment (keradus) [inline src/RuleSet/Sets/PERCS10RiskySet.php:28]: I get the idea behind overriding this method, but I think it shows the problem we are bypassing here.
looking at class name, we still do now know if it's PERCS 1.0 or 10. I wonder if we can adjust class name too?

File: src/RuleSet/Sets/PERCSRiskySet.php [hunk 7]
```diff
@@ -0,0 +1,46 @@
...
+namespace PhpCsFixer\RuleSet\Sets;
+
+use PhpCsFixer\RuleSet\AbstractRuleSetDescription;
+
+/**
+ * @internal
+ *
+ * @link https://www.php-fig.org/per/coding-style/
+ *
+ * This Ruleset always points to the latest version of PER-CS.
```
Comment (keradus) [inline src/RuleSet/Sets/PERCSRiskySet.php:24]: I wonder if we can have test for that?
I imagine someone creating PERCS1.2, but forgetting to update definition of PERCS

File: src/RuleSet/Sets/PERSet.php [hunk 8]
```diff
@@ -19,19 +19,19 @@
 /**
  * @internal
```
Comment (keradus) [inline src/RuleSet/Sets/PERSet.php:20]:
```suggestion
 * @internal
 * @deprecated
 * @TODO 4.0 remove me
```

File: src/RuleSet/Sets/PERCS10RiskySet.php (hunk 6 above)
Comment (Crell) [reply src/RuleSet/Sets/PERCS10RiskySet.php:28]: I am open to suggestions, given that we can't have periods in class names.  Using getName() is what @julienfalque suggested.  I have no particular preference, so whatever works.

File: src/RuleSet/Sets/PERCSRiskySet.php (hunk 7 above)
Comment (Crell) [reply src/RuleSet/Sets/PERCSRiskySet.php:24]: Off the cuff guess: A test that scans the folder for class names, filters for `PERCS`, orders alphabetically, and pops the first one?  Then use that to see if it resolves to the same name that `PERCSSet` points to?  Just spitballing.

Comment (keradus) [reply src/RuleSet/Sets/PERCSRiskySet.php:24]: i would only replace first part, you can use https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/src/RuleSet/RuleSets.php#L55 instead of scanning the folder

File: src/RuleSet/Sets/PERCS10RiskySet.php (hunk 6 above)
Comment (keradus) [reply src/RuleSet/Sets/PERCS10RiskySet.php:28]: `PERCS1x0RiskySet`? and `AbstractRuleSetDescription` can replace `\dx\d` with `\1.\2`

**Comment by Crell** [comment]
OK, I *think* I got it this time.  Let's see what the bot thinks.

**Comment by Crell** [comment]
Anyone else still interested in this PR, now that it's actually passing? :smile:

**Comment by keradus** [comment]
you put `per-cs1.0` in test fixture name, but keep `PERCS10Set` for Set classname file.
what do you think about using `1x0` in filename to indicate the dot? ref https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6707#discussion_r1060215806

File: src/RuleSet/Sets/PERCS1x0Set.php [hunk 9]
```diff
@@ -0,0 +1,44 @@
...
+    public function getRules(): array
+    {
+        return [
+            '@PSR12' => true,
+        ];
+    }
+
+    public function getDescription(): string
+    {
+        return 'Rules that follow `PER Coding Style 1.0 <https://www.php-fig.org/per/coding-style/>`_.';
```
Comment (kubawerlos) [inline src/RuleSet/Sets/PERCS1x0Set.php:42]: Is the `_` expected to be here?

Comment (Crell) [reply src/RuleSet/Sets/PERCS1x0Set.php:42]: It was in the PERSet class already, so I just kept it: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/src/RuleSet/Sets/PERSet.php#L35

Whether that was correct in the first place, I cannot say.  I just followed the existing pattern.

Comment (kubawerlos) [reply src/RuleSet/Sets/PERCS1x0Set.php:42]: Sorry for the fuss, apparently that how links work in RST files :)

**Review by kubawerlos — APPROVED** [review]

**Comment by Crell** [comment]
Anything else that needs to be done here?

**Comment by viktorprogger** [comment]
It's released today! But it's 2.0 instead of 1.1.
https://github.com/php-fig/per-coding-style/releases

**Comment by Crell** [comment]
All the more reason we should get this code merged soon so work can start on the 2x0 ruleset... 😄 

I'm not going to try and fix the conflicts until I hear from someone with merge access that this approach is acceptable.  No sense doing (more) work if it's not going to be accepted.

**Comment by Wirone** [comment]
@Crell I really would like to get it merged, but I need some time to get familiar with it. I believe all @keradus' doubts were addressed, @kubawerlos gave approval, for me it looks good at first glance (deprecate too general ruleset + introduce version specific rulesets), I just need to dig deeper into provided changes and previous discussions.

If you don't mind, I can rebase it to get rid of the conflicts and to trigger new CI pipeline. But of course you can do it too 🙂. Let me know, thanks in advance.

**Comment by Crell** [comment]
You'll probably have a chance to rebase it before I will, so feel free.  I am happy to answer questions about it, though "why is it done that way?" is mostly answered by "because some other PR reviewer said to and I don't know the tool well enough to disagree." 😄 

(Also updated the description to account for there now being a PER-CS 2, not 1.1.)

File: src/RuleSet/Sets/PERCSRiskySet.php [hunk 10]
```diff
@@ -0,0 +1,46 @@
...
+    public function getRules(): array
+    {
+        return [
+            '@PER-CS1.0:risky' => true,
+        ];
+    }
+
+    public function getDescription(): string
+    {
+        return 'Rules that follow the latest `PER Coding Style <https://www.php-fig.org/per/coding-style/>`_.';
```
Comment (Wirone) [inline src/RuleSet/Sets/PERCSRiskySet.php:44]:
```suggestion
        return 'Risky rules that follow the latest `PER Coding Style <https://www.php-fig.org/per/coding-style/>`_.';
```

File: src/RuleSet/Sets/PERCSSet.php [hunk 11]
```diff
@@ -0,0 +1,46 @@
...
+use PhpCsFixer\RuleSet\AbstractRuleSetDescription;
+
+/**
+ * @internal
+ *
+ * @see https://www.php-fig.org/per/coding-style/
+ *
+ * This Ruleset always points to the latest version of PER-CS.
+ * To fix on a specific version of PER-CS, use `PERCS10` (the 1.0 release),
+ * `PERCS11` (the 1.1 release), etc.
```
Comment (Wirone) [inline src/RuleSet/Sets/PERCSSet.php:26]:
```suggestion
 * To fix on a specific version of PER-CS, use `PER-CS1.0` (the 1.0 release) etc.
```

File: src/RuleSet/Sets/PERCSRiskySet.php [hunk 12]
```diff
@@ -0,0 +1,46 @@
...
+use PhpCsFixer\RuleSet\AbstractRuleSetDescription;
+
+/**
+ * @internal
+ *
+ * @see https://www.php-fig.org/per/coding-style/
+ *
+ * This Ruleset always points to the latest version of PER-CS.
+ * To fix on a specific version of PER-CS, use `PERCS10` (the 1.0 release),
+ * `PERCS11` (the 1.1 release), etc.
```
Comment (Wirone) [inline src/RuleSet/Sets/PERCSRiskySet.php:26]:
```suggestion
 * This Ruleset always points to the latest version of PER-CS risky rules.
 * To fix on a specific version of PER-CS risky rules, use `PER-CS1.0:risky` etc.
```

File: src/RuleSet/Sets/PERCSSet.php
Comment (Wirone) [inline src/RuleSet/Sets/PERCSSet.php:1]: I am not sure if it's a good idea to provide dynamic alias for latest PER-CS. It has several drawbacks:

- we need to [keep track of built-in sets](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6707#discussion_r1058584504) to prevent aliases getting out of sync
- we need to duplicate integration tests for the alias and will need to change them every time when new version of PER-CS is released
- if people out there use `@PER-CS` in their config it can suddenly change its behavior after Fixer upgrade. I believe people would rather prefer to change their config knowingly. It would be better to warn people somehow that they use outdated PER-CS.

**Review by Wirone — CHANGES_REQUESTED** [review]
General idea is OK for me, but I have some doubts, 2 most important are:

- [how to handle `PER-CS*` naming](#discussion_r1199502500)
- [should we provide alias for latest `PER-CS`?](#discussion_r1199507132)

File: src/RuleSet/Sets/PERCSSet.php
Comment (Crell) [reply src/RuleSet/Sets/PERCSSet.php:1]: I'm comfortable either way.  I can see the argument for it and against, and I'd probably use the pinned version anyway myself, so I defer to the maintainers.

File: src/RuleSet/Sets/PERCS1x0RiskySet.php [hunk 13]
```diff
@@ -0,0 +1,44 @@
...
+ * This source file is subject to the MIT license that is bundled
+ * with this source code in the file LICENSE.
+ */
+
+namespace PhpCsFixer\RuleSet\Sets;
+
+use PhpCsFixer\RuleSet\AbstractRuleSetDescription;
+
+/**
+ * @internal
```
[the remark this answers is not in the document]
Comment (Crell) [reply src/RuleSet/Sets/PERCS1x0RiskySet.php:20]: I think the intent on that one was to again discourage people from using `PER` specifically, since that should be deprecated and removed.  I may have over-interpreted it to include elsewhere.  We can remove them.

File: src/RuleSet/AbstractRuleSetDescription.php [hunk 14]
```diff
@@ -26,6 +28,7 @@ public function __construct()
     public function getName(): string
     {
         $name = substr(static::class, 1 + strrpos(static::class, '\\'), -3);
+        $name = Preg::replace('/\dx\d/', '\1.\2', $name);
```
[the remark this answers is not in the document]
Comment (Crell) [reply src/RuleSet/AbstractRuleSetDescription.php:31]: I really don't care about the class naming so I'm happy with basically anything, as long as it's clear which PER-CS version it references.

File: src/RuleSet/Sets/PERCS1x0RiskySet.php (hunk 13 above)
[the remark this answers is not in the document]
Comment (kubawerlos) [reply src/RuleSet/Sets/PERCS1x0RiskySet.php:20]: The classes are internal in terms of PHP API, so we can freely change it's signature.

File: src/RuleSet/Sets/PERCSSet.php
Comment (kubawerlos) [reply src/RuleSet/Sets/PERCSSet.php:1]: - I can imagine someone out of laziness/easiness would like to have `@PER-CS-lastest` (or whatever the name would be) and be rather prompt to re-format the code over remembering to update the set name every time a new version f PER-CS is released.
- we can skip the integration tests for the alias of the latest and instead have a test that it is indeed an alias of the latest version

➕ 1️⃣  to @Crell "I'd probably use the pinned version anyway myself", so maybe we can add an alias in the future if there is a big need for it.

File: src/RuleSet/Sets/PERCS1x0RiskySet.php (hunk 13 above)
[the remark this answers is not in the document]
Comment (Wirone) [reply src/RuleSet/Sets/PERCS1x0RiskySet.php:20]: But it does not make sense for me.. internal, but for public usage? 🤷‍♂️

[the remark this answers is not in the document]
Comment (kubawerlos) [reply src/RuleSet/Sets/PERCS1x0RiskySet.php:20]: For public usage via configuration as `@Symfony` set etc., the end user does not care how is the implementation made.

[the remark this answers is not in the document]
Comment (Wirone) [reply src/RuleSet/Sets/PERCS1x0RiskySet.php:20]: It makes sense 👌. Let's keep it.

**Comment by Wirone** [comment]
@Crell are you able to address last 2 concerns ([this](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6707#discussion_r1200855701) and [this](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6707#discussion_r1200862169))? We could finish it 🙂.

**Comment by Crell** [comment]
I thought you had taken over. 😄   Here's a stab at it.  Let's see if the bot approves.

Once this is done, we should figure out how to get PER-CS 2 implemented.  There are probably going to need to be a few new rules.

File: src/RuleSet/Sets/PERCS10RiskySet.php (hunk 6 above)
Comment (Wirone) [reply src/RuleSet/Sets/PERCS10RiskySet.php]: Let's use hardcoded values - we can easily change it in the future without breaking change, because name won't change, even if it's calculated automagically from class name.

PS. I removed that `Preg::replace()` which was added before at some point, because it wasn't used. If we actually need it, we can add it in separate PR.

File: src/RuleSet/AbstractRuleSetDescription.php [hunk 15]
```diff
@@ -28,7 +28,8 @@ public function __construct()
     public function getName(): string
     {
         $name = substr(static::class, 1 + strrpos(static::class, '\\'), -3);
-        $name = Preg::replace('/\dx\d/', '\1.\2', $name);
+        $name = Preg::replace('/(\d)x(\d)/', '\1.\2', $name);
+        $name = str_replace('_', '-', $name);
```
[the remark this answers is not in the document]
Comment (Wirone) [reply src/RuleSet/AbstractRuleSetDescription.php]: All changes in `AbstractRuleSetDescription` were reverted.

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
I am not 100% sure about current file/class naming (`PERCS1x0Set` and `PERCS1x0RiskySet`), because looking at other sets none of them uses `NxN` notation - both PHP and PHPUnit related sets have only numbers (like `PHPUnit100MigrationRiskySet`, but I believe we can change those files/classes names when needed, leaving actual set's name as-is. It is something that should be standardise somehow, but it's out of scope of this PR.

So.. I'm going to merge it and if anything looks wrong to @keradus we can change it later, before release.

**Comment by Wirone** [comment]
Thank you very much @Crell 🍻

**Comment by Crell** [comment]
Excellent!  Now someone can start on the PER-CS 2.0 ruleset. 😄
