### PR TITLE
bug: ListFilesCommand - fix computing of relative path

### LINKED ISSUE #6994: Replacing CWD in list-files command is too agressive
### Description

When using `list-files` command, all occurrences of `cwd` are replaced in file paths, but this is not checked the right way.

Example:
CWD: /opt
File: ./fixtures/opt_test.php
Result: ./fixtures._test.php

which is producing an error since this file doesn't exist. All this is caused by line 86 in ListFilesCommand.php

### Runtime version

PHP CS Fixer 3.15.1 BoY42 by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.3

### Used command

vendor/bin/php-cs-fixer list-files --config=.php-cs-fixer.dist.php 

### Configuration file

```
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__ . '/fixtures')
    ->in(__DIR__ . '/src')
    ->in(__DIR__ . '/tests')
    ->in(__DIR__ . '/config')
;

$config = new PhpCsFixer\Config();
return $config
    ->registerCustomFixers(new PhpCsFixerCustomFixers\Fixers())
    ->setRules([
        '@Symfony' => true,
        '@Symfony:risky' => true,
        'declare_strict_types' => true,
        'yoda_style' => false,
        'phpdoc_align' => false,
        'phpdoc_separation' => false,
        'array_syntax' => ['syntax' => 'short'],
        'ordered_imports' => [
            'imports_order' => ['class', 'function', 'const'],
        ],
        'trailing_comma_in_multiline' => [
            'elements' => ['arrays', 'arguments', 'parameters'],
        ],
        'method_argument_space' => [
            'on_multiline' => 'ensure_fully_multiline',
        ],
        'fopen_flags' => [
            'b_mode' => true,
        ],
        'no_unneeded_final_method' => false,  // conflicts with PHPStan
        'single_line_throw' => false, // broken with multiple throws in match cases
        'no_break_comment' => false,
        'native_function_invocation' => [
            'include' => [],
        ],
        'array_indentation' => true,
        PhpCsFixerCustomFixers\Fixer\MultilinePromotedPropertiesFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\NoTrailingCommaInSinglelineFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\PhpUnitAssertArgumentsOrderFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\PhpUnitDedicatedAssertFixer::name() => true,
        PhpCsFixerCustomFixers\Fixer\NoImportFromGlobalNamespaceFixer::name() => true,
])
    ->setFinder($finder)
;
```

### Code snippet that reproduces the problem

No code, since the issue is not caused by the code.

### PR DESCRIPTION
**Pull request by paulbalandan**
Fixes #6994

### CODE REVIEW

File: tests/Console/Command/ListFilesCommandTest.php [hunk 1]
```diff
@@ -41,6 +41,34 @@ public function testListWithConfig(): void
...
+     * @requires OS Linux|Darwin
+     *
+     * Skip test on Windows as `getcwd()` includes the drive letter with a colon `:` which is illegal in filenames.
+     */
+    public function testListFilesDoesNotCorruptListWithGetcwdInName(): void
+    {
+        $cwd = getcwd();
+        self::assertIsString($cwd, 'Cannot get the current working directory.');
+
+        $tempFile = __DIR__.'/../../Fixtures/ListFilesTest/using-getcwd/'.ltrim($cwd, '/').'-out.php';
```
Comment (Wirone) [inline tests/Console/Command/ListFilesCommandTest.php:54]: I don't like this idea - it creates a lot of nested directories in the `Fixtures` and since there is no any `.gitignore` rule for that, in case of failure it may lead to situation when you have some temp file for commit. Maybe we can utilise `sys_get_temp_dir()` and `chdir()` to create files in temp dir, then re-use that path within subdirectory? There are already tests in the project that leave some mess, I would like to avoid new ones 😅.

image

**Review by Wirone — CHANGES_REQUESTED** [review]

**Comment by paulbalandan** [comment]
I cannot understand why macOS is failing. 🤔

**Comment by Wirone** [comment]
@paulbalandan annoying thing to test, isn't it? 🙈

File: tests/Console/Command/ListFilesCommandTest.php (hunk 1 above)
Comment (paulbalandan) [reply tests/Console/Command/ListFilesCommandTest.php]: Very annoying to test, indeed. I reverted using `sys_get_temp_dir()` as I don't know what's happening on macOS. Anyway, I think I used proper post-cleanup so I think this should be okay now.

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
Thank you @paulbalandan 🍻
