### PR TITLE
fix: `BinaryOperatorSpacesFixer` - align correctly when multiple shifts occurs in single line

### LINKED ISSUE #5605: `binary_operator_spaces` problem with several shifts in single line
### Code snippet that reproduces the problem

file.php:
```php
<?php

$planPercent = $periodFilled['plan']/$maxPlan * 100;
$factPercent = $periodFilled['actual']/$maxPlan * 100;

```
.php_cs:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
;

return PhpCsFixer\Config::create()
    ->setFinder($finder)
    ->setRules([
        'binary_operator_spaces' => ['default' => 'align_single_space_minimal']
    ])
    ->setLineEnding("\n")
;

```
### Fixing
```
 php-cs-fixer fix -vvv file.php
PHP CS Fixer 2.18.5 Remote Void by Fabien Potencier and Dariusz Ruminski (e0f6d05)
Runtime: PHP 7.4.16
Loaded config default from "<masked>/.php_cs".
Using cache file ".php_cs.cache".
Paths from configuration file have been overridden by paths provided as command arguments.
F
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) file.php (binary_operator_spaces)

Fixed all files in 0.011 seconds, 12.000 MB memory used
```
#### Actual result
```
 cat file.php                  
<?php

$planPercent = $periodFilled['plan']   / $maxPlan   * 100;
$factPercent = $periodFilled['actual'] / $maxPlan * 100;
```

#### Expected result
```
 cat file.php                  
<?php

$planPercent = $periodFilled['plan']   / $maxPlan * 100;
$factPercent = $periodFilled['actual'] / $maxPlan * 100;
```

### PR DESCRIPTION
**Pull request by wadakatu**
Fixes #5605 

Hope it helps.

Prev PR #7365

### CODE REVIEW

File: tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php [hunk 1]
```diff
@@ -556,6 +556,30 @@ function A(){}[$a] = $a[$c];
...
+             $testD = $testE["abcdef"] / $testF * 100;
+            ',
+            '<?php
+             $testA = $testB["abc"]/$testC * 100;
+             $testD = $testE["abcdef"]/$testF * 100;
+            ',
+            ['default' => BinaryOperatorSpacesFixer::ALIGN_SINGLE_SPACE_MINIMAL],
+        ];
+
+        yield 'multiple shifts in single line (failed)' => [
```
Comment (wadakatu) [inline tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php:572]: However, this case is failed because of this error below.

```
There was 1 failure:
1) PhpCsFixer\Tests\Fixer\Operator\BinaryOperatorSpacesFixerTest::testConfigured with data set "multiple shifts in single line (failed)" ('<?php\n             $testA = ...      ', '<?php\n             $testA = ...      ', array('align_single_space_minimal'))
Tokens collection built on expected code must not be marked as changed after fixing.
Failed asserting that true is false.

/PHP-CS-Fixer/tests/Test/AbstractFixerTestCase.php:519
/PHP-CS-Fixer/tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php:86
```

**Comment by wadakatu** [comment]
@Wirone 

HI.
I am sorry for the late submission.
Regarding [this error message](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7365#issuecomment-1852401826), I would like to get your adivice.
Please let me know if there are any questions or concerns about the changes that I made.
Thank you.

File: tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php (hunk 1 above)
Comment (kubawerlos) [reply tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php:572]: The check that fails means that the expected code was changed.

If you replace the input snippet to `null` (lines 577-580 in the diff) and add `var_dump($code);` at the beginning of `PhpCsFixer\Tokenizer\Tokens::setCode`, the you will see that code was changing:
```cli
kub@:~/code/friendsofphp/PHP-CS-Fixer(master)$ ./vendor/bin/phpunit ./tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php --filter=failed
PHPUnit 9.6.15 by Sebastian Bergmann and contributors.

F                                                                                                                                               1 / 1 (100%)string(156) "<?php
             $testA = $testB["abc"]    / $testC * 10000000    * 100;
             $testD = $testE["abcdef"] / $testF * 10000000000 * 100;
            "
string(156) "<?php
             $testA = $testB["abc"]    / $testC * 10000000    * 100;
             $testD = $testE["abcdef"] / $testF * 10000000000 * 100;
            "
string(153) "<?php
             $testA = $testB["abc"]    / $testC * 10000000 * 100;
             $testD = $testE["abcdef"] / $testF * 10000000000 * 100;
            "
string(156) "<?php
             $testA = $testB["abc"]    / $testC * 10000000    * 100;
             $testD = $testE["abcdef"] / $testF * 10000000000 * 100;
            "
string(156) "<?php
             $testA = $testB["abc"]    / $testC * 10000000    * 100;
             $testD = $testE["abcdef"] / $testF * 10000000000 * 100;
            "


Time: 00:00.012, Memory: 8.00 MB

There was 1 failure:

1) PhpCsFixer\Tests\Fixer\Operator\BinaryOperatorSpacesFixerTest::testConfigured with data set "multiple shifts in single line (failed)" ('<?php\n
   $testA = ...      ', null, array('align_single_space_minimal'))
Tokens collection built on expected code must not be marked as changed after fixing.
Failed asserting that true is false.

/home/kuba/code/friendsofphp/PHP-CS-Fixer/tests/Test/AbstractFixerTestCase.php:569
/home/kuba/code/friendsofphp/PHP-CS-Fixer/tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php:86

FAILURES!
Tests: 1, Assertions: 3, Failures: 1.
```

Comment (Wirone) [reply tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php:572]: The problem here was that original `$tokens` was cloned and overridden (with `$tokens->setCode()`) for each `$toAlign` operator, even if code was not changed. I did some changes, so original `$tokens` is cloned only once, and content is overridden at the end only once too, but _only if cloned tokens' content was changed_. It should improve performance because collection is not re-created every time, but also it fixes problem with checking if expected code is changed after applying fixer.

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
Thank you very much @wadakatu 🍻!

**Comment by wadakatu** [comment]
@Wirone 
I should thank you too!
I saw your changes, but I don't think I could have come up with them myself.

Anyway, I'm glad that the issue has been fixed.
Cheers! 🍻

**Comment by ddevsr** [comment]
Since this changed, @wadakatu @Wirone.

```diff
-            'name'       => ['type' => 'varchar', 'constraint' => 31],
-            'uid'        => ['type' => 'varchar', 'constraint' => 31],
-            'class'      => ['type' => 'varchar', 'constraint' => 63],
-            'icon'       => ['type' => 'varchar', 'constraint' => 31],
-            'summary'    => ['type' => 'varchar', 'constraint' => [25]
+            'name'       => ['type' => 'varchar', 'constraint'       => 31],
+            'uid'        => ['type' => 'varchar', 'constraint'        => 31],
+            'class'      => ['type' => 'varchar', 'constraint'      => 63],
+            'icon'       => ['type' => 'varchar', 'constraint'       => [31]
+            'summary'    => ['type' => 'varchar', 'constraint'    => 255],
```

My rule
```bash
'binary_operator_spaces'                   => [
                'default'   => 'single_space',
                'operators' => [
                    '='  => 'align_single_space_minimal',
                    '=>' => 'align_single_space_minimal',
                    '||' => 'align_single_space_minimal',
                    '.=' => 'align_single_space_minimal',
                ],
            ],
```

**Comment by Wirone** [comment]
@ddevsr please create new issue instead of commenting closed PR. I've updated your comment with an code snippet and CLI command for issue reproduction, please use it when reporting issue. Sorry for the problem caused by this change.

**Comment by wadakatu** [comment]
@Wirone @ddevsr 

I apologize for any inconvenience caused by this change. Finding an immediate solution may be challenging. 
Therefore, I propose we first revert the change, and then I will work on finding a solution. Does that sound acceptable?

**Comment by Wirone** [comment]
It's not that easy, because I am unable to make a release, only @keradus can do it. Let's not rush things, I believe it's not that crucial.
