### PR TITLE
bug: PhpdocTypesFixer - do not change case of array keys

### LINKED ISSUE #6772: Lowercase native constants in @var tag
### Description

Fixer fixes array field names with same name as native constants in @var tag.

### Runtime version

PHP CS Fixer 3.14.2 Oliva
PHP runtime: 8.1.13

### Code snippet that reproduces the problem

```php
/** @var array<int, array{Field: string, Type: string, Null: string, Extra: string}> $tableDescribe */
$tableDescribe = $conn->fetchAllAssociative('describe '.$tableName);
  ```

becomes

```php
/** @var array<int, array{Field: string, Type: string, null: string, Extra: string}> $tableDescribe */
$tableDescribe = $conn->fetchAllAssociative('describe '.$tableName);
  ```

### PR DESCRIPTION
**Pull request by kubawerlos**
Fixes #6772

### CODE REVIEW

File: tests/Fixer/Phpdoc/PhpdocTypesFixerTest.php [hunk 1]
```diff
@@ -30,186 +30,150 @@ final class PhpdocTypesFixerTest extends AbstractFixerTestCase
...
+        $this->fixer->configure($configuration);
+
         $this->doTest($expected, $input);
     }
 
-    public function testWindowsLinebreaks(): void
+    public static function provideFixCases(): iterable
     {
-        $this->doTest(
+        yield 'windows linereaks' => [
```
Comment (Wirone) [inline tests/Fixer/Phpdoc/PhpdocTypesFixerTest.php:45]:
```suggestion
        yield 'windows line breaks' => [
```

**Review by Wirone — APPROVED** [review]

**Review by keradus — APPROVED** [review]
