### PR TITLE
fix: `fully_qualified_strict_types` must honor template/local type identifiers

### LINKED ISSUE #7720: `leading_backslash_in_global_namespace` breaks generics
## Bug report

Currently `fully_qualified_strict_types` with `leading_backslash_in_global_namespace` option fixes local generics symbols, example:

```diff
 <?php
 
 class MethodGenerics
 {
     /**
      * @template T of \Exception
      * @param \Closure(): T $fx
-     * @return T
+     * @return \T
      */
     public function makeException(\Closure $fx)
     {
         return $fx();
     }
 }
 
 /**
  * @template T of \Exception
  */
 class ClassGenerics
 {
     /**
      * @param \Closure(): T $fx
-     * @return T
+     * @return \T
      */
     public function makeException(\Closure $fx)
     {
         return $fx();
     }
 }
```

This is wrong, there is nothing to be fixed.

I expect the same also for local in-class type aliases [2].

[1] https://phpstan.org/blog/generics-in-php-using-phpdocs#type-variables
[2] https://phpstan.org/writing-php-code/phpdoc-types#local-type-aliases

### PR DESCRIPTION
**Pull request by mvorisek**
fix #7720

### CODE REVIEW

File: src/Fixer/Import/FullyQualifiedStrictTypesFixer.php [hunk 1]
```diff
@@ -63,6 +63,11 @@ final class FullyQualifiedStrictTypesFixer extends AbstractFixer implements Conf
      */
     private array $symbolsForImport = [];
 
+    /**
```
Comment (mvorisek) [inline src/Fixer/Import/FullyQualifiedStrictTypesFixer.php:66]: the CI seems to be broken by some unrelated change - https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/actions/runs/7514529067/job/20457502110

Comment (Wirone) [reply src/Fixer/Import/FullyQualifiedStrictTypesFixer.php:66]: Probably related to PHPUnit `ctype` requirement in 10.5.6. It's working now.

**Comment by mvorisek** [comment]
@Wirone thank you very much for merging #7719. This PR was based on it, so I rebased it. Review welcomed.

**Comment by mvorisek** [comment]
This fix is here for a month, can we move on so it can be part of the next release, please?

File: src/Fixer/Import/FullyQualifiedStrictTypesFixer.php [hunk 2]
```diff
@@ -303,12 +316,19 @@ protected function applyFix(\SplFileInfo $file, Tokens $tokens): void
                     } elseif ($discoverSymbolsPhase && !\defined('T_ATTRIBUTE') && $tokens[$index]->isComment() && Preg::match('/#\[\s*('.self::REGEX_CLASS.')/', $tokens[$index]->getContent(), $matches)) { // @TODO: drop when PHP 8.0+ is required
                         $this->determineShortType($matches[1], $uses, $namespaceName);
                     } elseif ($tokens[$index]->isGivenKind(T_DOC_COMMENT)) {
+                        Preg::matchAll('/\*\h*@(?:psalm-|phpstan-)?(?:template(?:-covariant|-contravariant)?|(?:import-)?type)\h+('.TypeExpression::REGEX_IDENTIFIER.')(?!\S)/i', $tokens[$index]->getContent(), $matches);
```
Comment (Wirone) [inline src/Fixer/Import/FullyQualifiedStrictTypesFixer.php:319]: `psalm-`/`phpstan-` prefixes and `-covariant`/`-contravariant` suffixes are not covered with tests. Maybe it's possible to make simple, single test case for them?

File: src/Fixer/Import/FullyQualifiedStrictTypesFixer.php [hunk 3]
```diff
@@ -354,6 +374,25 @@ private function refreshUsesCache(array $uses): void
...
+        if (str_contains($symbol, '\\')) { // optimization only
+            return false;
+        }
+
+        if ((new TypeAnalysis($symbol))->isReservedType()) {
+            return true;
+        }
+
+        foreach ($this->reservedIdentifiers as $reservedIdentifiers) {
+            if (isset($reservedIdentifiers[$symbol])) {
```
Comment (Wirone) [inline src/Fixer/Import/FullyQualifiedStrictTypesFixer.php:388]: After quick look it's not super clear why `$this->reservedIdentifiers` is iterated as `$reservedIdentifiers` (plural again), maybe something like this could help:

```suggestion
        foreach ($this->reservedIdentifiers as $scopeReservedIdentifiers) {
            if (isset($scopeReservedIdentifiers[$symbol])) {
```

I mean, it should be more readable that these identifiers are scope-narrowed. Naming is just a proposal 🙂.

File: src/Fixer/Import/FullyQualifiedStrictTypesFixer.php [hunk 4]
```diff
@@ -278,10 +283,18 @@ protected function applyFix(\SplFileInfo $file, Tokens $tokens): void
...
                 for ($index = $namespace->getScopeStartIndex(); $index < $namespace->getScopeEndIndex() + $indexDiff; ++$index) {
                     $origSize = \count($tokens);
 
-                    if ($discoverSymbolsPhase && $tokens[$index]->isGivenKind($classyKinds)) {
+                    if ($tokens[$index]->equals('{')) {
+                        ++$openedCurlyBrackets;
+                    } if ($tokens[$index]->equals('}')) {
+                        unset($this->reservedIdentifiers[$openedCurlyBrackets]);
+                        --$openedCurlyBrackets;
+                    } elseif ($discoverSymbolsPhase && $tokens[$index]->isGivenKind($classyKinds)) {
```
Comment (Wirone) [inline src/Fixer/Import/FullyQualifiedStrictTypesFixer.php:297]: If I understand correctly, each set of reserved identifiers exists only between `{` and `}`, these are effectively merged as long as current token index is inside `{}`, and last one is unset when closing brace is found. That means the set of identifiers grows with each nested `{}`.

My concerns about this (thinking out loud) is: should these identifiers always be merged from first `{` up to the last (current) `{`? I mean, test cases don't have `@template` on class level, and it's just my guess, but if there's a template `T` on class level and then somewhere inside you have anonymous class with template `T2`, the `T` symbol should be allowed to use within that anonymous class since it's a different scope 🤔? It's getting too complicated for token-based logic 😅.

**Review by Wirone — CHANGES_REQUESTED** [review]
As this is not the easiest change, you should understand it's not always possible to review it on-the-fly 😉. Last weeks were tough when it comes to reviews, as I worked on my own initiatives and they took most of my free time. Anyway, I finally had some time.

Personally I took a look at the diff between input and expected output in test cases, so here it is for easier understanding:

image

image

File: src/Fixer/Import/FullyQualifiedStrictTypesFixer.php (hunk 4 above)
Comment (mvorisek) [reply src/Fixer/Import/FullyQualifiedStrictTypesFixer.php:297]: The implementation should be how it works in reality. Can you provide a https://phpstan.org/try repro?

File: src/Fixer/Import/FullyQualifiedStrictTypesFixer.php (hunk 3 above)
Comment (mvorisek) [reply src/Fixer/Import/FullyQualifiedStrictTypesFixer.php:388]: I agree. The iterated plural variable should be kept, any idea how to name the property better?

File: src/Fixer/Import/FullyQualifiedStrictTypesFixer.php (hunk 2 above)
Comment (mvorisek) [reply src/Fixer/Import/FullyQualifiedStrictTypesFixer.php:319]: I will add some tests with `leading_backslash_in_global_namespace` for these.

File: src/Fixer/Import/FullyQualifiedStrictTypesFixer.php (hunk 3 above)
Comment (mvorisek) [reply src/Fixer/Import/FullyQualifiedStrictTypesFixer.php]: addressed

File: src/Fixer/Import/FullyQualifiedStrictTypesFixer.php (hunk 4 above)
Comment (Wirone) [reply src/Fixer/Import/FullyQualifiedStrictTypesFixer.php]: Don't have time to figure it out, so maybe we can just improve it _if_ problem occurs 😉.

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
Thank you @mvorisek 🍻!

File: src/Fixer/Import/FullyQualifiedStrictTypesFixer.php (hunk 4 above)
Comment (mvorisek) [reply src/Fixer/Import/FullyQualifiedStrictTypesFixer.php]: Thank you ❤
