### PR TITLE
fix: Runner - handle no files while in parallel runner

### LINKED ISSUE #8013: cs-fixer multicore bug with --path-mode and a specified file
### Problem description

```
$ php-cs-fixer fix -vvv --using-cache=no --path-mode=intersection -- .php-cs-fixer.dist.php
PHP CS Fixer 3.57.0 7th Gear by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.3.7
Running analysis on 16 cores with 10 files per process.
Parallel runner is an experimental feature and may be unstable, use it at your own risk. Feedback highly appreciated!
Loaded config default from "/home/easteregg/src/wrapped/.php-cs-fixer.dist.php".
    0 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]
```

:point_up: this just hangs

### Minimal reproducer

running with this config: https://github.com/verfriemelt-dot-org/wrapped/blob/master/.php-cs-fixer.dist.php#L55

```shell
cd $(mktemp -d)
git clone https://github.com/verfriemelt-dot-org/wrapped .
git checkout dae18e31aa003c818abe359f0e18378f89e19e12
composer install
php-cs-fixer fix -vvv --using-cache=no --path-mode=intersection -- .php-cs-fixer.dist.php
```

### Fixer version

3.57.0

### PHP version

8.3.7

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

### PR DESCRIPTION
**Pull request by keradus**
closes #8013

@Wirone , i worked here in quickfix mode, ideally it should be covered by tests too

### CODE REVIEW

**Review by Wirone — APPROVED** [review]
It was spawning 0 processes so it was never going out of the React loop? Yeah, missed that case 😅. Let's add tests later for that.

File: src/Runner/Runner.php [hunk 1]
```diff
@@ -130,20 +130,28 @@ public function __construct(
...
      * @param \Traversable<array-key, \SplFileInfo> $fileIterator
      */
     public function setFileIterator(iterable $fileIterator): void
     {
-        // @TODO consider to drop this method and make iterator parameter obligatory in constructor,
-        // more in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7777/files#r1590447581
         $this->fileIterator = $fileIterator;
+
+        // Required only for main process (calculating workers count)
+        $this->fileCount = \count(iterator_to_array($fileIterator));
```
Comment (keradus) [inline src/Runner/Runner.php:143]: for proper solution, I would consider to either fully remove `fileCount` var, or to keep that iterator_to_array result stored as `fileIterator`

File: src/Runner/Runner.php [hunk 2]
```diff
@@ -130,20 +130,28 @@ public function __construct(
...
     }
 
     /**
      * @return _RunResult
      */
     public function fix(): array
     {
+        if (0 === $this->fileCount) {
```
Comment (keradus) [inline src/Runner/Runner.php:151]: we do not need to bother fixing anything in anyway, if there are no files to be fixed.

File: src/Runner/Runner.php [hunk 3]
```diff
@@ -222,7 +230,10 @@ private function fixParallel(): array
 
         $processesToSpawn = min(
             $this->parallelConfig->getMaxProcesses(),
-            (int) ceil($this->fileCount / $this->parallelConfig->getFilesPerProcess())
+            max(
+                1,
```
Comment (keradus) [inline src/Runner/Runner.php:234]: `$this->fileCount` may be empty, and then we do not even run `fixParallel()`

but also `$this->fileCount` may not be empty, but after filtering out cached files etc, we have no files to be run. with that, i put another guard here with `max(1, ...)`

File: src/Runner/Runner.php (hunk 1 above)
Comment (Wirone) [reply src/Runner/Runner.php:143]: Wouldn't it lead to higher memory usage, since everything would be stored as an array? Right now we store the iterator, which only has the definition of a set, and additionally we store the count for further calculations. Yeah, maybe it's not super elegant, but perf-wise it is probably better?

Comment (keradus) [reply src/Runner/Runner.php:143]: that's why ideally we do not need the fileCount at all
