### PR TITLE
fix: Allow using cache when running in Docker distribution

### LINKED ISSUE #7768: Cache is not supported using the official docker image
### Description

The cache file is not generated using the docker official image.

According to the documentation:

> The cache is supported only when the tool was downloaded as a phar file or installed via Composer.

But I don't really see why the docker image should not support it as we can fetch it back thanks to volume binding.

Possible related: #6996.

### Runtime version

```
PHP CS Fixer 3.47.0 Big Changes by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.2.14
```

### Used command

```
❯ docker run --rm -t -v ${PWD}:${PWD} -w ${PWD} ghcr.io/php-cs-fixer/php-cs-fixer:3.47.0-php8.2 check --using-cache=yes                       
PHP CS Fixer 3.47.0 Big Changes by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.2.14
Loaded config default from "/home/sullivan/p/gitlab.com/ss-open/ci/recipes/.php-cs-fixer.dist.php".
 6/6 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

   1) rector.php
   2) .fixtures/fixture.php

Found 2 of 6 files that can be fixed in 0.038 seconds, 14.000 MB memory used

❯ ls .php-cs-fixer.cache                 
ls: cannot access '.php-cs-fixer.cache': No such file or directory
```

### Configuration file

```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->ignoreDotFiles(false)
    ->ignoreVCS(true)
    ->ignoreVCSIgnored(true)
;

$config = new PhpCsFixer\Config();

return $config->setRules([
        '@PSR1' => true,
        '@PSR12' => true,
        'strict_param' => true,
        'array_syntax' => ['syntax' => 'short'],
    ])
    ->setRiskyAllowed(true)
    ->setFinder($finder)
;
```

### Code snippet that reproduces the problem

N/A

### PR DESCRIPTION
**Pull request by Wirone**
Fixes #7768.

-----

```shell
docker build --target dist -t fixer:local .
docker run --rm -it -v $(pwd):/code --entrypoint="" fixer:local sh

/code # php-cs-fixer check
PHP CS Fixer 3.48.1-DEV Small Changes by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.3.2
Loaded config default from "/code/.php-cs-fixer.php".
 1070/1070 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


Found 0 of 1070 files that can be fixed in 40.647 seconds, 26.000 MB memory used

/code # php-cs-fixer check
PHP CS Fixer 3.48.1-DEV Small Changes by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.3.2
Loaded config default from "/code/.php-cs-fixer.php".
Using cache file "/code/.php-cs-fixer.cache.json".
 1070/1070 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


Found 0 of 1070 files that can be fixed in 0.136 seconds, 16.000 MB memory used
```

Second run inside Docker container uses cache.

### CODE REVIEW

File: src/ToolInfo.php [hunk 1]
```diff
@@ -98,6 +98,11 @@ public function isInstalledByComposer(): bool
         return $this->isInstalledByComposer;
     }
 
+    public function isRunInsideDocker(): bool
+    {
+        return is_file('/.dockerenv') && str_starts_with(__FILE__, '/fixer/');
```
Comment (keradus) [inline src/ToolInfo.php:103]: can we document in code where the `/fixer/` coming from?

**Review by keradus — APPROVED** [review]

File: src/Console/ConfigurationResolver.php [hunk 2]
```diff
@@ -479,7 +479,7 @@ public function getUsingCache(): bool
             }
         }
```
Comment (keradus) [inline src/Console/ConfigurationResolver.php:480]: in raised issue we have mentioned this docs:
> The cache is supported only when the tool was downloaded as a phar file or installed via Composer.

probably we can update it in this PR to reflect Docker image too
