### PR TITLE
bug: Fix `return_assignment` not formatting when variables are used in `catch` and `finally`

### LINKED ISSUE #6691: return_assignment should not be formatted when the variable is used in catch and finally
## Bug report

```shell
# ./vendor/bin/php-cs-fixer -V
PHP CS Fixer 3.13.0 Oliva by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.0.23
```

**config:**

```php
<?php

declare(strict_types=1);

return (new PhpCsFixer\Config())
    ->setRules([
        '@PHP74Migration'            => true,
        '@PHP74Migration:risky'      => true,
        '@Symfony'                   => true,
        '@Symfony:risky'             => true,
        '@DoctrineAnnotation'        => true,
        'return_assignment'          => true,
    ])
    ->setRiskyAllowed(true)
;
```

### Code snippet that reproduces the problem

**code:**

```php
<?php

declare(strict_types=1);

function add($a, $b): mixed
{
    try {
        $result = $a + $b;

        return $result;
    } catch (\Throwable $th) {
        throw $th;
    } finally {
        echo 'result:', $result, \PHP_EOL;
    }
}

add(1, 2);

```

**result:**

```shell
# ./vendor/bin/php-cs-fixer fix --dry-run --diff test2.php 
Loaded config default from "/mnt/d/projects/test/.php-cs-fixer.php".
Using cache file ".php-cs-fixer.cache".
   1) test2.php
      ---------- begin diff ----------
--- /mnt/d/projects/test/test2.php
+++ /mnt/d/projects/test/test2.php
@@ -5,9 +5,7 @@
 function add($a, $b): mixed
 {
     try {
-        $result = $a + $b;
-
-        return $result;
+        return $a + $b;
     } catch (\Throwable $th) {
         throw $th;
     } finally {

      ----------- end diff -----------


Checked all files in 0.017 seconds, 14.000 MB memory used
```

### PR DESCRIPTION
**Pull request by Yurunsoft**
fix #6691

### CODE REVIEW

**Review by kubawerlos — CHANGES_REQUESTED** [review]
Please add a test case with an input code like this:
```php
<?php
function foo()
{
    if (isSomeContiotion()) {
        $result = getSomeResult();
        return $result;
    }

    try {
        $result = getResult();
        return $result;
    } catch (\Throwable $exception) {
        error_log($exception->getMessage());
    } finally {
        baz($result);
    }
}
```

File: src/Fixer/ReturnNotation/ReturnAssignmentFixer.php [hunk 1]
```diff
@@ -278,6 +278,20 @@ private function fixFunction(Tokens $tokens, int $functionIndex, int $functionOp
                 continue;
             }
 
+            // Check if there is a finally block and if the variable is used in it
+            $tryIndex = $tokens->getPrevTokenOfKind($returnVarIndex, [[T_TRY]]);
+            if (null !== $tryIndex && $tryIndex > $functionOpenIndex && $tryIndex < $functionCloseIndex) {
```
Comment (kubawerlos) [inline src/Fixer/ReturnNotation/ReturnAssignmentFixer.php:283]: Can we have this extracted to a separate method to have it easier to comprehend in the future?

**Review by kubawerlos — CHANGES_REQUESTED** [review]
One more test case please, this time with input:
```php
<?php
function foo()
{
    try {
        $result = getResult();
        return $result;
    } catch (\Throwable $exception) {
        error_log($exception->getMessage());
    }

    if (isSomeContiotion()) {
        $result = getSomeResult();
        return $result;
    }

    try {
        $result = $a + $b;
        return $result;
    } catch (\Throwable $th) {
        throw $th;
    } finally {
        echo "result:", $result, \PHP_EOL;
    }
}
```

File: src/Fixer/ReturnNotation/ReturnAssignmentFixer.php [hunk 2]
```diff
@@ -468,4 +474,58 @@ private function isOpenBraceOfMatch(Tokens $tokens, int $index): ?int
 
         return $tokens[$index]->isGivenKind(T_MATCH) ? $index : null;
     }
+
+    private function isUsedInCatchOrFinally(Tokens $tokens, int $returnVarIndex, int $functionOpenIndex, int $functionCloseIndex): bool
+    {
+        // Find try
+        $tryIndex = $tokens->getPrevTokenOfKind($returnVarIndex, [[T_TRY]]);
+        if (null === $tryIndex || $tryIndex <= $functionOpenIndex || $tryIndex >= $functionCloseIndex) {
```
Comment (kubawerlos) [inline src/Fixer/ReturnNotation/ReturnAssignmentFixer.php:482]:
```suggestion
        if (null === $tryIndex || $tryIndex <= $functionOpenIndex) {
```
The last condition is not possible, right? `$tryIndex` is smaller than `$functionCloseIndex` when we enter the `isUsedInCatchOrFinally` function and with `getPrevTokenOfKind` value of `$tryIndex` can be only smaller.

File: tests/Fixer/ReturnNotation/ReturnAssignmentFixerTest.php [hunk 3]
```diff
@@ -620,6 +620,178 @@ function Foo() {
                     }
                 ',
             ],
+            'try catch' => [
+                '<?php
+                function foo()
+                {
+                    if (isSomeContiotion()) {
```
Comment (kubawerlos) [inline tests/Fixer/ReturnNotation/ReturnAssignmentFixerTest.php:627]: I know that this "typo" is from my suggestion, but you might want to fix it as it will be your name in `git blame` for it 😛

**Review by kubawerlos — DISMISSED** [review]
No more tricky cases from me, only small changes, and will be good.

**Comment by Yurunsoft** [comment]
@kubawerlos Thank you very much, I have solved all these problems.

**Review by Wirone — CHANGES_REQUESTED** [review]
I believe we need test case with multiple `catch` blocks, something like:

```php
function foo() {
    try {
        $bar = bar();

        return $bar;
    } catch (\LogicException $e) {
        echo "catch ... ";
    } catch (\RuntimeException $e) {
        echo $bar;
    }
}
```

(Writing code on mobile 😩😅)

**Comment by Yurunsoft** [comment]
> I believe we need test case with multiple `catch` blocks, something like:
> 
> ```
> function foo() {
>     try {
>         $bar = bar();
> 
>         return $bar;
>     } catch (\LogicException $e) {
>         echo "catch ... ";
>     } catch (\RuntimeException $e) {
>         echo $bar;
>     }
> }
> ```
> 
> (Writing code on mobile 😩😅)

Thanks, it has been fixed.

File: tests/Fixer/ReturnNotation/ReturnAssignmentFixerTest.php [hunk 4]
```diff
@@ -1165,6 +1165,20 @@ function add($a, $b): mixed
                 }
                 ',
             ],
+            'try finally2' => [
```
Comment (Wirone) [inline tests/Fixer/ReturnNotation/ReturnAssignmentFixerTest.php:1168]:
```suggestion
            'try with multiple catch blocks' => [
```

There's no `finally` here 😉. And cases should be described in a way that intention is clear.

**Comment by Wirone** [comment]
@Yurunsoft to speed up things I've rebased your branch and added [more test cases](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6960/commits/2b5f12437b9244be51b6a6594b5b5ca7572ff15d), please update your local branch to current remote revision.

**Comment by Wirone** [comment]
@kubawerlos @Yurunsoft FYI: I looked into current tests and [there is case for `$$`](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/08ec0679e5c61c2a7d2be3c0ca5c63c5c5c4ba3e/tests/Fixer/ReturnNotation/ReturnAssignmentFixerTest.php#L907-L916) which IMHO does not make sense 😅. It could be changed to `return $$c;` and would work the same, so technically this is wrong test case. But the good part is that case like below also works properly too (is not changed):

```php
<?php
function foo()
{
    try {
        $result = getResult();
        return $result;
    } catch (\Throwable $exception) {
        error_log($exception->getMessage());
    } finally {
        $foo = 'result';
        baz($$foo);
    }
}
```

Do we want to change the test case for `$$` here, to reflect that scenario better?

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
Thank you @Yurunsoft 🍻
