### PR TITLE
feat: Introduce `check` command (alias for `fix --dry-run`)

### LINKED ISSUE #7307: Introduce `check` command as an alias for `fix --dry-run`
Explicit entrypoint which's name suggest only linting (without fixing) would be good for the users. It has to be only lightweight proxy to the `fix` command that provides and passes all the available options from/to main command, only enforcing `--dry-run`.

_Accepted by @keradus in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/7301#discussioncomment-7013948_

### PR DESCRIPTION
**Pull request by Wirone**
Fixes #7307.

I am not sure about inheritance approach, but I believe it was the quickest way to achieve it, without refactoring much more. Let me know what you think 🙂.

### CODE REVIEW

File: src/Console/Command/CheckCommand.php [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+/**
+ * @author Greg Korba <greg@codito.dev>
+ *
+ * @internal
+ */
+#[AsCommand(name: 'check', description: 'Runs configured rules against configured files/directories without applying fixes.')]
+final class CheckCommand extends FixCommand
+{
+    protected static $defaultName = 'check';
+    protected static $defaultDescription = 'Runs configured rules against configured files/directories without applying fixes.';
```
Comment (keradus) [inline src/Console/Command/CheckCommand.php:31]: maybe more like `Check if configured files/directories comply with configured rules`?

File: phpstan.dist.neon [hunk 2]
```diff
@@ -16,6 +16,7 @@ parameters:
     ignoreErrors:
         - '/^Class [a-zA-Z\\]+ extends @final class PhpCsFixer\\(ConfigurationException\\InvalidConfigurationException|ConfigurationException\\InvalidFixerConfigurationException|Tokenizer\\Tokens)\.$/'
         - '/^\$this\(PhpCsFixer\\Tokenizer\\Tokens\) does not accept PhpCsFixer\\Tokenizer\\Token\|null\.$/'
+        - '/^Class PhpCsFixer\\Console\\Command\\CheckCommand extends @final class PhpCsFixer\\Console\\Command\\FixCommand\.$/'
```
Comment (keradus) [inline phpstan.dist.neon:19]: ouch

Comment (Wirone) [reply phpstan.dist.neon:19]: Yeah, not the best thing, but without `@final` annotation tests fail. So in order to use inheritance approach we either need to ignore this in PHPStan or exclude `FixCommand` from test which enforces classes being `final` 🤷‍♂️.

File: src/Console/Command/FixCommand.php [hunk 3]
```diff
@@ -227,7 +227,7 @@ protected function execute(InputInterface $input, OutputInterface $output): int
             [
                 'allow-risky' => $input->getOption('allow-risky'),
                 'config' => $passedConfig,
-                'dry-run' => $input->getOption('dry-run'),
+                'dry-run' => $this->isDryRun($input),
```
Comment (keradus) [inline src/Console/Command/FixCommand.php:230]: that means for scope of FixCommand, someone could use `isDryRun()`, but could still use `->getOption('dry-run')`. And when using in inheriting class CheckCommand, they will have different results.

Maybe instead of introducing 2nd way to get the value (custom getter), we could cal `setOption('dry-run', ...)` in child class?

File: src/Console/Command/FixCommand.php [hunk 4]
```diff
@@ -159,7 +162,7 @@ public function getHelp(): string
 
                 <info>$ php %command.full_name% --verbose --show-progress=dots</info>
 
-            By using <command>--using-cache</command> option with `yes` or `no` you can set if the caching
+            By using <comment>--using-cache</comment> option with `yes` or `no` you can set if the caching
```
Comment (keradus) [inline src/Console/Command/FixCommand.php:165]: myself, i would make independent PR , that could get merged earlier.
(but no worry, no need to extract now)

File: src/Console/Command/FixCommand.php [hunk 5]
```diff
@@ -190,25 +193,22 @@ public function getHelp(): string
...
-                    new InputOption('format', '', InputOption::VALUE_REQUIRED, 'To output results in other formats.'),
-                    new InputOption('stop-on-violation', '', InputOption::VALUE_NONE, 'Stop execution on first violation.'),
-                    new InputOption('show-progress', '', InputOption::VALUE_REQUIRED, 'Type of progress indicator (none, dots).'),
-                ]
-            )
-            ->setDescription('Fixes a directory or a file.')
-        ;
+        $this->setDefinition(
+            [
+                new InputArgument('path', InputArgument::IS_ARRAY, 'The path that rules be run against (file or directory).'),
```
Comment (keradus) [inline src/Console/Command/FixCommand.php:198]: should we use plural, as it's IS_ARRAY ?

File: phpstan.dist.neon (hunk 2 above)
Comment (Wirone) [reply phpstan.dist.neon:19]: I think we could refactor this later, while keeping 100% backward compatibility for `check` command. But people could already use it as a quick-win solution.

BTW. same thing is already ignored 2 lines above, just realised this 😅. I could just improve the regex.

File: src/Console/Command/FixCommand.php (hunk 3 above)
Comment (Wirone) [reply src/Console/Command/FixCommand.php:230]: I already tried that, but since I re-create command's definition and filter out `--dry-run` option (so it's not displayed in the `--help`), it can't be set with `$input->setOption('dry-run', true)` before invoking `parent::execute($input, $output)`. It ends up with an error:

image

We could get rid of `isDryRun()` if we don't mind displaying `--dry-run` as an `check` command's option 🙂.

File: src/Console/Command/FixCommand.php (hunk 4 above)
Comment (Wirone) [reply src/Console/Command/FixCommand.php:165]: Yeah, it would be better because it does not belong here, but making PR for that would be too much probably 😅.

File: src/Console/Command/FixCommand.php (hunk 5 above)
Comment (Wirone) [reply src/Console/Command/FixCommand.php]: I did not want to touch it here, because `path` options is passed to config resolver which also uses `path`, so we either would have discrepancy in the naming or I would need to go deeper and I don't want to do it here. I've improved options' descriptions, though.

Comment (keradus) [reply src/Console/Command/FixCommand.php]: yeah, I meant the description only :+1:

File: src/Console/Command/FixCommand.php (hunk 3 above)
Comment (keradus) [reply src/Console/Command/FixCommand.php:230]: i'm not fully happy here, but the only other solution i found so far was to have yet-another-parent like `FixAbstract` and `Fix extends FixAbstract` + `Check extends FixAbstract`, but also not the best.
let's keep as-is unless anything better comes to anyone mind

Comment (Wirone) [reply src/Console/Command/FixCommand.php:230]: What do you mean by "keep as-is"? Merge in this form or keep PR opened until we figure something out 😅?

**Review by keradus — APPROVED** [review]

File: src/Console/Command/FixCommand.php (hunk 3 above)
Comment (keradus) [reply src/Console/Command/FixCommand.php:230]: ok, i see the confusion

i meant i will merge it now
