### PR TITLE
fix: NoUnneededBracesFixer - improve handling of global namespace

### LINKED ISSUE #7636: Parse error when @PhpCsFixer rule is enabled
### Description

When running php-cs-fixer on some code that only has namespace and a class I got  an error about an unexpected `;` but the code has no `;` in it. This only happens with the `@PhpCsFixer` rule enabled, if I remove this rule it runs successfully. Example code at the bottom.

The error:
```
[PhpCsFixer\Linter\LintingException]
Parse error: syntax error, unexpected token ";", expecting "{" on line 3.

Applied fixers: no_unneeded_braces, class_definition, braces_position, statement_indentation, single_line_empty_body, blank_line_after_namespace, single_blank_line_at_eof
```

### Runtime version

PHP CS Fixer version: 3.43.1
PHP runtime version: 8.2.13

### Used command

`php vendor/bin/php-cs-fixer fix -vvv`

### Configuration file

```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__);

$config = new PhpCsFixer\Config();

return $config->setRules([
    '@PhpCsFixer' => true,
])
    ->setFinder($finder);

```

### Code snippet that reproduces the problem

  ```php
<?php

namespace {
    class Foo {}
}
  ```

### PR DESCRIPTION
**Pull request by keradus**
closes #7636

### CODE REVIEW

File: src/Fixer/ControlStructure/NoUnneededBracesFixer.php [hunk 1]
```diff
@@ -134,9 +134,17 @@ private function clearIfIsOverCompleteNamespaceBlock(Tokens $tokens): void
 
         $index = $tokens->getNextTokenOfKind(0, [[T_NAMESPACE]]);
 
-        do {
+        $namespaceisNamed = false;
```
Comment (Wirone) [inline src/Fixer/ControlStructure/NoUnneededBracesFixer.php:137]:
```suggestion
        $namespaceIsNamed = false;
```

File: src/Fixer/ControlStructure/NoUnneededBracesFixer.php [hunk 2]
```diff
@@ -134,9 +134,17 @@ private function clearIfIsOverCompleteNamespaceBlock(Tokens $tokens): void
...
+
+        $index = $tokens->getNextMeaningfulToken($index);
+        while ($tokens[$index]->isGivenKind([T_STRING, T_NS_SEPARATOR])) {
             $index = $tokens->getNextMeaningfulToken($index);
-        } while ($tokens[$index]->isGivenKind([T_STRING, T_NS_SEPARATOR]));
+            $namespaceisNamed = true;
```
Comment (Wirone) [inline src/Fixer/ControlStructure/NoUnneededBracesFixer.php:142]:
```suggestion
            $namespaceIsNamed = true;
```

File: src/Fixer/ControlStructure/NoUnneededBracesFixer.php [hunk 3]
```diff
@@ -134,9 +134,17 @@ private function clearIfIsOverCompleteNamespaceBlock(Tokens $tokens): void
...
+        }
+
+        if (!$namespaceisNamed) {
```
Comment (Wirone) [inline src/Fixer/ControlStructure/NoUnneededBracesFixer.php:145]:
```suggestion
        if (!$namespaceIsNamed) {
```

**Review by Wirone — APPROVED** [review]
