### PR TITLE
bug: Fix type error when using paths intersection mode

### LINKED ISSUE #6718: Fatal error on PHP 8.1.13 using path-mode intersection
## Bug report

I encountered a problem running php-cs-fixer on PHP 8.1.13 using `path-mode` intersection. Here is the command I am running:

`php bin/php-cs-fixer fix --diff --dry-run -v --path-mode=intersection -- ./MyClass.php` which results in

```
Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, CallbackFilterIterator given in .../vendor/friendsofphp/php-cs-fixer/src/Console/Command/FixCommand.php:318
```

### Details

- PHP version: 8.1.13
- PHP CS Fixer version: 3.13.1

### PR DESCRIPTION
**Pull request by julienfalque**
Fixes #6718 and replaces #6719.

### CODE REVIEW

File: tests/Console/Command/FixCommandTest.php [hunk 1]
```diff
@@ -93,7 +106,7 @@ private function getDefaultArguments(): array
         return [
             'path' => [__FILE__],
             '--path-mode' => 'override',
-            '--allow-risky' => true,
```
Comment (keradus) [inline tests/Console/Command/FixCommandTest.php:96]: nice

File: tests/Console/Command/FixCommandTest.php [hunk 2]
```diff
@@ -29,6 +30,18 @@
  */
 final class FixCommandTest extends TestCase
 {
+    public function testIntersectionPathMode(): void
+    {
+        $cmdTester = $this->doTestExecute([
+            '--path-mode' => 'intersection',
```
Comment (keradus) [inline tests/Console/Command/FixCommandTest.php:36]:
```suggestion
            '--path-mode' => 'intersection',
            '--show-progress' => 'none',
```

just to make sure which `if` branch we enter

File: tests/Console/Command/FixCommandTest.php [hunk 3]
```diff
@@ -29,6 +30,19 @@
  */
 final class FixCommandTest extends TestCase
 {
+    public function testIntersectionPathMode(): void
```
Comment (keradus) [inline tests/Console/Command/FixCommandTest.php:33]: awesome to have the test for this!

**Review by keradus — APPROVED** [review]

**Comment by keradus** [comment]
kudos @julienfalque !
