### PR TITLE
fix: Do not shorten FQN for class resolution if imported symbol is not a class

### LINKED ISSUE #7652: `fully_qualified_strict_types` - conversion from `Foo\Bar::class` to `Bar::class` should not happen for imported function
```php
<?php

use function Symfony\Component\String\u;

echo Symfony\Component\String\u::class;
echo "\n";
echo u::class;
```

ref https://github.com/symfony/symfony/pull/53233#discussion_r1438916844

### PR DESCRIPTION
**Pull request by Wirone**
Fixes #7652

### CODE REVIEW

**Comment by mvorisek** [comment]
in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7704 there is a fix already :)

**Comment by Wirone** [comment]
@mvorisek Are you telling me I wasted my time for implementing this 😩? Eeehhhh....

File: src/Fixer/Import/FullyQualifiedStrictTypesFixer.php [hunk 1]
```diff
@@ -334,29 +354,32 @@ protected function applyFix(\SplFileInfo $file, Tokens $tokens): void
...
     /**
-     * @param array<string, string> $uses
+     * @param _Uses $uses
      */
     private function refreshUsesCache(array $uses): void
     {
-        if ($this->cacheUsesLast === $uses) {
-            return;
-        }
+        foreach ($uses as $kind => $kindUses) {
```
Comment (mvorisek) [inline src/Fixer/Import/FullyQualifiedStrictTypesFixer.php:361]: the foreach must be put right before the other foreach

File: src/Tokenizer/Analyzer/NamespaceUsesAnalyzer.php [hunk 2]
```diff
@@ -203,8 +203,11 @@ private function getNearestQualifiedName(Tokens $tokens, int $index): array
             $index = $tokens->getNextMeaningfulToken($index);
         }
 
+        /** @var class-string $fqn */
+        $fqn = $fullName;
```
Comment (Wirone) [inline src/Tokenizer/Analyzer/NamespaceUsesAnalyzer.php:207]: I had to do that because of PHPStan, which expects `class-string`, but infers `string` from the code above (rightfully), and I couldn't do `/** @var class-string $fullName */` before `return` because Fixer wants to change it to `//` comment and then PHPStan can't see the enforced type 😕.

File: src/Fixer/Import/FullyQualifiedStrictTypesFixer.php (hunk 1 above)
Comment (Wirone) [reply src/Fixer/Import/FullyQualifiedStrictTypesFixer.php:390]: Can you explain a bit more?

Comment (mvorisek) [reply src/Fixer/Import/FullyQualifiedStrictTypesFixer.php:390]: It is evident, the lines after the first `foreach` are unrelated to the loop, ie. must be placed before the loop.

**Comment by Wirone** [comment]
@kubawerlos do you have an idea why [this fails](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/actions/runs/9305289118/job/25611872183?pr=7705)? It imports and shortens `CoversClass` like [here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/actions/runs/9305289118/job/25611872183?pr=7705#step:5:583), but at the same time leaves FQCN like [here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/actions/runs/9305289118/job/25611872183?pr=7705#step:5:603) 😕. I need to go now, will be AFK until late evening, if anyone can take a look I will be grateful.

**Comment by Wirone** [comment]
@mvorisek I've added this rule explicitly to the "highest" config, but it sometimes works and sometimes not 🤔.

**Comment by kubawerlos** [comment]
Well, it looks fine on my PC 😁

I see in the job's log:
```
2024-05-30T15:37:38.9384682Z   79) tests/RuleSet/Sets/PSR12RiskySetTest.php
2024-05-30T15:37:38.9384841Z       ---------- begin diff ----------
2024-05-30T15:37:38.9385237Z --- /home/runner/work/PHP-CS-Fixer/PHP-CS-Fixer/tests/RuleSet/Sets/PSR12RiskySetTest.php
2024-05-30T15:37:38.9385637Z +++ /home/runner/work/PHP-CS-Fixer/PHP-CS-Fixer/tests/RuleSet/Sets/PSR12RiskySetTest.php
2024-05-30T15:37:38.9385766Z @@ -14,9 +14,10 @@
2024-05-30T15:37:38.9385856Z  
2024-05-30T15:37:38.9386008Z  namespace PhpCsFixer\Tests\RuleSet\Sets;
2024-05-30T15:37:38.9386097Z  
2024-05-30T15:37:38.9386246Z +use PhpCsFixer\RuleSet\Sets\PSR12RiskySet;
2024-05-30T15:37:38.9386337Z +
2024-05-30T15:37:38.9386427Z  /**
2024-05-30T15:37:38.9386531Z   * @internal
2024-05-30T15:37:38.9386642Z - *
2024-05-30T15:37:38.9386854Z - * @covers \PhpCsFixer\RuleSet\Sets\PSR12RiskySet
2024-05-30T15:37:38.9386948Z   */
2024-05-30T15:37:38.9387193Z +#[\PHPUnit\Framework\Attributes\CoversClass(PSR12RiskySet::class)]
2024-05-30T15:37:38.9387421Z  final class PSR12RiskySetTest extends AbstractSetTestCase {}
2024-05-30T15:37:38.9387426Z 
2024-05-30T15:37:38.9387577Z       ----------- end diff -----------
```

but when I run locally from the branch I have:
```
kub@:~/code/friendsofphp/PHP-CS-Fixer(codito/7652-ignore-class-resolution-for-function)$ php php-cs-fixer fix --diff --config .php-cs-fixer.php-highest.php tests/RuleSet/Sets/PSR12RiskySetTest.php --dry-run
PHP CS Fixer 3.58.2-DEV 7th Gear by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.3.7
Running analysis on 8 cores with 10 files per process.
Parallel runner is an experimental feature and may be unstable, use it at your own risk. Feedback highly appreciated!
Loaded config default from ".php-cs-fixer.php-highest.php".
Using cache file ".php-cs-fixer.cache".
Paths from configuration file have been overridden by paths provided as command arguments.
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

   1) tests/RuleSet/Sets/PSR12RiskySetTest.php
      ---------- begin diff ----------
--- /home/kuba/code/friendsofphp/PHP-CS-Fixer/tests/RuleSet/Sets/PSR12RiskySetTest.php
+++ /home/kuba/code/friendsofphp/PHP-CS-Fixer/tests/RuleSet/Sets/PSR12RiskySetTest.php
@@ -14,9 +14,11 @@

 namespace PhpCsFixer\Tests\RuleSet\Sets;

+use PhpCsFixer\RuleSet\Sets\PSR12RiskySet;
+use PHPUnit\Framework\Attributes\CoversClass;
+
 /**
  * @internal
- *
- * @covers \PhpCsFixer\RuleSet\Sets\PSR12RiskySet
  */
+#[CoversClass(PSR12RiskySet::class)]
 final class PSR12RiskySetTest extends AbstractSetTestCase {}

      ----------- end diff -----------
```
and I would expect that in CI here too

**Comment by kubawerlos** [comment]
I guess we can move updating `.php-cs-fixer.php-highest.php` to separate PR and get the fix done.

**Comment by Wirone** [comment]
@kubawerlos it works differently when you apply the "highest" ruleset to a single file or to the whole codebase. The CI outcome can be reproduced locally by running the exact command that is run in the CI, and the running `composer cs:check` - some files have FQCNs in attributes 😩. I don't understand why, PHPUnit's rule has higher priority and is applied before `fully_qualified_strict_types`, so the added attribute should be fixed. It does not make sense because some files are fixed fully, some skip the FQCN import step 🤷‍♂️.

**Comment by Wirone** [comment]
It was magically* fixed since last rebase, so it's a good moment to review it and finally provide the fix for importing symbols 😁 .

\* or it was fixed with some other PR merged since May 31st 🤷‍♂️🙂.

**Review by kubawerlos — APPROVED** [review]

File: src/Fixer/Import/FullyQualifiedStrictTypesFixer.php (hunk 1 above)
Comment (mvorisek) [reply src/Fixer/Import/FullyQualifiedStrictTypesFixer.php]: @Wirone I think the merged change is still wrong - ll413-414 must go before 411
