### PR TITLE
fix: Support named args in `ParallelConfigFactory::detect()`

### LINKED ISSUE #8025: `ParallelConfigFactory` using named parameters behaves unexpectedly when omiting first argument
### Problem description

```php
$config->setParallelConfig(ParallelConfigFactory::detect(processTimeout: 300));
```

:point_up: the above code will create unexpected parallel config values. `$processTimeout` argument will be used as number of files per process instead. This is due to `array_filter` removing "falsy" values from argument list.

```php
return new ParallelConfig(
    ...array_filter(
        [self::$cpuDetector->getCount(), $filesPerProcess, $processTimeout],
        static fn ($value): bool => null !== $value
    )
);
```

### Minimal reproducer

```php
$config = new \PhpCsFixer\Config();
$config->setParallelConfig(\PhpCsFixer\Runner\Parallel\ParallelConfigFactory::detect(processTimeout: 300));
```
or
```php
$config = new \PhpCsFixer\Config();
$config->setParallelConfig(\PhpCsFixer\Runner\Parallel\ParallelConfigFactory::detect(null, 300));
```

### Fixer version

3.57.1

### PHP version

8.3

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

### PR DESCRIPTION
**Pull request by Wirone**
Fixes #8025

### CODE REVIEW

File: src/Runner/Parallel/ParallelConfigFactory.php [hunk 1]
```diff
@@ -47,11 +47,19 @@ public static function detect(
...
+            [
+                'maxProcesses' => self::$cpuDetector->getCount(),
+                'filesPerProcess' => $filesPerProcess,
+                'processTimeout' => $processTimeout,
+            ],
+            static fn ($value): bool => null !== $value
         );
+
+        if (\PHP_VERSION_ID < 8_00_00) {
+            $args = array_values($args);
```
Comment (Steveb-p) [inline src/Runner/Parallel/ParallelConfigFactory.php:60]: This will "only" fix PHP 8+ arguments, as 7.4 will still move `processTimeout` argument into 2nd place, right?

Comment (Wirone) [reply src/Runner/Parallel/ParallelConfigFactory.php]: Yeah, I focused too much on named args, but even though I've tested it on PHP 7.4, I did not take `ParallelConfigFactory::detect(null, 360)` into consideration, where 360 would be shifted left and used as process per file, not as timeout. I've simplified it and factory now reuses `ParallelConfig`'s constants with default values.

File: src/Runner/Parallel/ParallelConfig.php [hunk 2]
```diff
@@ -19,8 +19,8 @@
  */
 final class ParallelConfig
 {
-    private const DEFAULT_FILES_PER_PROCESS = 10;
-    private const DEFAULT_PROCESS_TIMEOUT = 120;
+    public const DEFAULT_FILES_PER_PROCESS = 10;
+    public const DEFAULT_PROCESS_TIMEOUT = 120;
```
Comment (keradus) [inline src/Runner/Parallel/ParallelConfig.php:23]:
```suggestion
    /** @internal */
    public const DEFAULT_FILES_PER_PROCESS = 10;
    /** @internal */
    public const DEFAULT_PROCESS_TIMEOUT = 120;
```

File: src/Runner/Parallel/ParallelConfigFactory.php [hunk 3]
```diff
@@ -48,10 +48,9 @@ public static function detect(
         }
 
         return new ParallelConfig(
-            ...array_filter(
-                [self::$cpuDetector->getCount(), $filesPerProcess, $processTimeout],
-                static fn ($value): bool => null !== $value
-            )
+            self::$cpuDetector->getCount(),
+            $filesPerProcess ?? ParallelConfig::DEFAULT_FILES_PER_PROCESS,
+            $processTimeout ?? ParallelConfig::DEFAULT_PROCESS_TIMEOUT
```
Comment (keradus) [inline src/Runner/Parallel/ParallelConfigFactory.php:53]: 👍🏻 so clean now

File: tests/Runner/Parallel/ParallelConfigFactoryTest.php [hunk 4]
```diff
@@ -61,4 +61,39 @@ public function testDetectConfigurationWithParams(): void
...
+        ]);
+
+        self::assertSame(5, $config2->getFilesPerProcess());
+        self::assertSame(300, $config2->getProcessTimeout());
+
+        // Only first argument provided, but via named argument
+        $config3 = \call_user_func_array([ParallelConfigFactory::class, 'detect'], ['filesPerProcess' => 7]);
+
+        self::assertSame(7, $config3->getFilesPerProcess());
+        self::assertSame(120, $config3->getProcessTimeout());
```
Comment (keradus) [inline tests/Runner/Parallel/ParallelConfigFactoryTest.php:97]: we could use `DEFAULT_PROCESS_TIMEOUT` now, in that case.

Comment (Wirone) [reply tests/Runner/Parallel/ParallelConfigFactoryTest.php:97]: IMHO values in asserts should not reuse constants because then you don't catch that something has changed (assert follows const value automatically, so you always have proper value in the assert). Tests should fail when constants are changed, as this is a change in public contract. Do you have a different experience?

File: src/Runner/Parallel/ParallelConfig.php (hunk 2 above)
Comment (Wirone) [reply src/Runner/Parallel/ParallelConfig.php:23]: I thought about making it internal, but then I thought that maybe it's not that bad to allow it to use it in the configs if someone wants to do it?

Comment (keradus) [reply src/Runner/Parallel/ParallelConfig.php:23]: I prefer to keep BC promise minimal, let's make it internal and open if someone would request it.

File: tests/Runner/Parallel/ParallelConfigFactoryTest.php (hunk 4 above)
Comment (keradus) [reply tests/Runner/Parallel/ParallelConfigFactoryTest.php:97]: if method is supposed to calculate the value, yes, it should be hardcoded/ninja value.
Yet if method is expected to return given special value (here - default value) "as is", then it's OK to rely on given constant. In such test you care if test returned given special value, not what that value actually is.

Beside of request to not keep the existence of those constants under BC promise, changing the value of the constant under BC promise is not BC break ([ref](https://symfony.com/doc/current/contributing/code/bc.html#changing-classes))

**Review by keradus — APPROVED** [review]
