### PR TITLE
fix: `SingleSpaceAroundConstructFixer` - handle alternative syntax

### LINKED ISSUE #8316: `single_space_around_construct` ignored for alternative syntax
### Problem description

The `single_space_around_construct` rule does not apply to `if` statements with [alternative syntax](https://www.php.net/manual/en/control-structures.alternative-syntax.php). If a file contains any alternative syntax, the `single_space_around_construct` rule is even skipped for the whole file.

Other rules seem to handle normal and alternative syntax equally. As far as I can tell the documentation of the `single_space_around_construct` rule does not exclude the alternative syntax. Therefor, this seems to be an unintentional bug.

I will open a PR with a possible fix in a few minutes.

### Minimal reproducer

file.php:
```
<?php if(true): ?>
    A
<?php elseif(false): ?>
    B
<?php else: ?>
    C
<?php endif; ?>
```

Command:
```
source/vendor/bin/php-cs-fixer fix --rules=single_space_around_construct file.php
```

Expected contents of file.php (notice space after `if` and `elseif`):
```
<?php if (true): ?>
    A
<?php elseif (false): ?>
    B
<?php else: ?>
    C
<?php endif; ?>
```

However, contents of file.php are unchanged.

### Fixer version

3.65.0

### PHP version

8.3.7

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

### PR DESCRIPTION
**Pull request by timsmid**
Fixes #8316.

### CODE REVIEW

**Review by keradus — COMMENTED** [review]
-0

i'm explicitly encouraging to not use alternative syntax, only case I see for it is in templates, but I also encourage to use any templates engine rather than directly PHP for it.

with that, I'm not gonna spend any time to support alternative syntax myself, but OKish to merge validated changes provided by userland.

File: tests/Fixer/LanguageConstruct/SingleSpaceAroundConstructFixerTest.php [hunk 1]
```diff
@@ -1910,6 +1932,28 @@ public static function provideFixWithIfCases(): iterable
...
+            '<?php if ($foo === $bar): endif;',
+            '<?php if
+
+($foo === $bar): endif;',
+        ];
+
+        yield [
+            '<?php if /* foo */($foo === $bar): endif;',
+            '<?php if/* foo */($foo === $bar): endif;',
+        ];
```
Comment (kubawerlos) [inline tests/Fixer/LanguageConstruct/SingleSpaceAroundConstructFixerTest.php:1956]:
```suggestion
        ];

    yield [
            '<?php if (true): else: endif;',
        ];
```

File: tests/Fixer/LanguageConstruct/SingleSpaceAroundConstructFixerTest.php [hunk 2]
```diff
@@ -1910,6 +1932,32 @@ public static function provideFixWithIfCases(): iterable
...
+
+    yield [
```
Comment (kubawerlos) [inline tests/Fixer/LanguageConstruct/SingleSpaceAroundConstructFixerTest.php:1958]:
```suggestion
        yield [
```

**Review by kubawerlos — APPROVED** [review]

**Comment by kubawerlos** [comment]
Thank you @timsmid
