### PR TITLE
fix: ClassDefinitionFixer for anonymous class with phpdoc/attribute on separate line

### LINKED ISSUE #7541: `class_definition` is reformatting phpdoc for anonymous class
## Bug report

Code like:
```
$model = new
/**
 * @property string $x
 */
class() extends AtkModel {
    public int $p;
};
```

is currently fixed to:
```
$model = new /**
 * @property string $x
 */ class() extends AtkModel {
    public int $p;
};
```

I would expect no change and all wrongly formatted code fixed to the 1st example.

related with https://github.com/phpstan/phpstan/issues/7345#issuecomment-1848966265

### PR DESCRIPTION
**Pull request by mvorisek**
fix #7541

### CODE REVIEW

**Comment by mvorisek** [comment]
Can this PR be merged, please?

**Comment by mvorisek** [comment]
Rebased on the latest master. Can this PR be merged and included in the next release, please?

File: src/Fixer/ClassNotation/ClassDefinitionFixer.php [hunk 1]
```diff
@@ -362,15 +363,37 @@ private function makeClassyDefinitionSingleLine(Tokens $tokens, int $startIndex,
     {
         for ($i = $endIndex; $i >= $startIndex; --$i) {
             if ($tokens[$i]->isWhitespace()) {
-                if ($tokens[$i - 1]->isComment() || $tokens[$i + 1]->isComment()) {
+                if (str_contains($tokens[$i]->getContent(), "\n")) {
+                    if (\defined('T_ATTRIBUTE')) { // @TODO: drop condition and else when PHP 8.0+ is required
+                        if ($tokens[$i - 1]->isGivenKind(CT::T_ATTRIBUTE_CLOSE) || $tokens[$i + 1]->isGivenKind(T_ATTRIBUTE)) {
+                            continue;
```
Comment (kubawerlos) [inline src/Fixer/ClassNotation/ClassDefinitionFixer.php:369]: Can we extract some logic to separate methods? This is 4th level `if`, and all 4 are already in `for` loop.

File: src/Fixer/ClassNotation/ClassDefinitionFixer.php [hunk 2]
```diff
@@ -362,15 +363,37 @@ private function makeClassyDefinitionSingleLine(Tokens $tokens, int $startIndex,
...
+                        }
+                    } else {
+                        if (($tokens[$i - 1]->isComment() && str_ends_with($tokens[$i - 1]->getContent(), ']'))
+                            || ($tokens[$i + 1]->isComment() && str_starts_with($tokens[$i + 1]->getContent(), '#['))
```
Comment (kubawerlos) [inline src/Fixer/ClassNotation/ClassDefinitionFixer.php:373]: In all other fixers we do not handle attributes in PHP 7, why do we want to start here? Is it even necessary? Can we only check for comment here?

File: src/Fixer/ClassNotation/ClassDefinitionFixer.php [hunk 3]
```diff
@@ -362,15 +363,37 @@ private function makeClassyDefinitionSingleLine(Tokens $tokens, int $startIndex,
...
-                        $content = $tokens[$i + 1]->getContent();
+                    continue;
+                }
 
-                        if (!('#' === $content || str_starts_with($content, '//'))) {
-                            $tokens[$i] = new Token([T_WHITESPACE, ' ']);
-                        }
+                if ($tokens[$i + 1]->isComment()) {
+                    $content = $tokens[$i + 1]->getContent();
+                    if (!str_starts_with($content, '//')) {
```
Comment (kubawerlos) [inline src/Fixer/ClassNotation/ClassDefinitionFixer.php:395]: What if we change to `!str_ends_with($content, "\n")`? Wouldn't that cover single-line comments and attribute-comment-in-PHP-7?

File: src/Fixer/ClassNotation/ClassDefinitionFixer.php (hunk 1 above)
Comment (mvorisek) [reply src/Fixer/ClassNotation/ClassDefinitionFixer.php:369]: The last level if call `continue` of the top loop, thus not easily.

File: src/Fixer/ClassNotation/ClassDefinitionFixer.php (hunk 2 above)
Comment (mvorisek) [reply src/Fixer/ClassNotation/ClassDefinitionFixer.php:373]: standard comments are handled below regularly, we need to skip only attribute comments

File: src/Fixer/ClassNotation/ClassDefinitionFixer.php (hunk 3 above)
Comment (mvorisek) [reply src/Fixer/ClassNotation/ClassDefinitionFixer.php:395]: This is not related to this PR. `!str_ends_with($content, "\n")` was already present and it is needed for already existing tests to pass.

**Comment by mvorisek** [comment]
@Wirone can this and my other 2 non-draft PRs be merged?

**Comment by Wirone** [comment]
@mvorisek there's no need to ping me, because I have notifications for everything in the repo, so I am aware of your PRs, but as I [said before](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7622#discussion_r1436944958) I had a holidays until January 3rd 🙂. Spending time [with family](https://twitter.com/_Codito_/status/1741611529676501105), AFK.

**Comment by mvorisek** [comment]
Also let's please merge this PR. And happy new year to you and your beatiful family! ❤

**Comment by mvorisek** [comment]
Can this PR be merged, please?

**Comment by mvorisek** [comment]
@Wirone is there any feedback left?

**Comment by mvorisek** [comment]
This issue is here for more than a month. Can it be please merged soon? Thank you ❤

File: tests/Fixer/ClassNotation/ClassDefinitionFixerTest.php [hunk 4]
```diff
@@ -305,6 +305,67 @@ class#
...
+                class() {};
+                EOF,
+        ];
+
+        yield 'multiple attributes on separate line' => [
+            <<<'EOF'
+                <?php
+                $a = new
+                #[FOO]
+                #[\Ns\Bar]
```
Comment (Wirone) [inline tests/Fixer/ClassNotation/ClassDefinitionFixerTest.php:322]: [This is valid code](https://3v4l.org/70gJp) that is handled by this fixer currently, but maybe we could include it in test case to avoid regression?

```suggestion
                #[FOO] // Added because ...
                #[\Ns\Bar]
```

File: src/Fixer/ClassNotation/ClassDefinitionFixer.php
Comment (Wirone) [inline src/Fixer/ClassNotation/ClassDefinitionFixer.php:1]: Instead of that wild previous token / next token logic, couldn't we just verify if there are comments or attributes between `new` and `class`? If there is any kind of meta information, we could leave it as-is. Does current implementation handle something I did not think about?

Comment (mvorisek) [reply src/Fixer/ClassNotation/ClassDefinitionFixer.php:1]: We need to detect attribute comment explicitly in order to fully pass with existing tests.

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
Thanks @mvorisek 🍻!
