### PR TITLE
chore: fix CI for Windows

### LINKED ISSUE #8323: allow symfony/process 7.2+
7.2 caused our tests to fail, we shall figure out way to have this working again
ref #8322

### PR DESCRIPTION
**Pull request by kubawerlos**
Seeing the new test added in v7.2.0 (at the bottom of diff at https://github.com/symfony/process/compare/v7.1.8...v7.2.0) I guess it makes sense.

closes #8323

### CODE REVIEW

File: tests/Linter/ProcessLinterProcessBuilderTest.php [hunk 1]
```diff
@@ -61,7 +61,7 @@ public function testPrepareCommandOnPhpOnWindows(string $executable, string $fil
      */
     public static function providePrepareCommandOnPhpOnWindowsCases(): iterable
     {
-        yield 'Linux-like' => ['php', 'foo.php', 'php -l foo.php'];
+        yield 'Linux-like' => ['php', 'foo.php', 'c:\tools\php\php.EXE -l foo.php'];
```
Comment (keradus) [inline tests/Linter/ProcessLinterProcessBuilderTest.php:64]: are you able to validate on non-CI env if this is good? was a while since I coded on Windows, but I was close to believe it shall be php.exe, not php.EXE

Comment (kubawerlos) [reply tests/Linter/ProcessLinterProcessBuilderTest.php:64]: I thought it should be `php.exe`, but apparentely not: https://github.com/symfony/process/blob/v7.2.0/Tests/ProcessTest.php#L1703

Comment (keradus) [reply tests/Linter/ProcessLinterProcessBuilderTest.php:64]: but that's still the CI env (and for some random executable).

I would love to validate it behaves properly for PHP executable on Windows in non-CI env, as everywhere I see php.exe and not php.EXE ([example](https://stackoverflow.com/questions/42136850/execute-php-file-with-php-exe))

Comment (Wirone) [reply tests/Linter/ProcessLinterProcessBuilderTest.php:64]: Maybe we should always use `ExecutableFinder` to normalize path for PHP binary? That should fix the problem for Windows and wouldn't break anything for other OSes.

Comment (mvorisek) [reply tests/Linter/ProcessLinterProcessBuilderTest.php:64]: Probably, `c:\tools\php\php.EXE` is definitely wrong, `C:` drive does not even have to exist on a Windows systen.

Comment (keradus) [reply tests/Linter/ProcessLinterProcessBuilderTest.php:64]: @Wirone , i believe we do already use ExecutableFinder:
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/src/Linter/ProcessLinter.php#L47-L68

File: composer.json [hunk 2]
```diff
@@ -42,7 +42,7 @@
         "symfony/polyfill-mbstring": "^1.28",
         "symfony/polyfill-php80": "^1.28",
         "symfony/polyfill-php81": "^1.28",
-        "symfony/process": "^5.4 || ^6.0 || ^7.0 <7.2",
+        "symfony/process": "^5.4 || ^6.0 || ^7.0",
```
Comment (keradus) [inline composer.json:45]: looks good

```
C:\github\test-win-path>type run.php
<?php

require "vendor/autoload.php";

use Symfony\Component\Process\PhpExecutableFinder;

$executableFinder = new PhpExecutableFinder();

echo "executable found by new PhpExecutableFinder()->find(false)\n";
echo $executableFinder->find(false);
echo "\n\n";

echo "executable found by new PhpExecutableFinder()->find(true)\n";
echo $executableFinder->find(true);
echo "\n\n";
```

````
C:\github\test-win-path>where php
C:\tools\php82\php.exe
```

```
C:\github\test-win-path>composer info -D
symfony/process 7.2.0 Executes commands in sub-processes
```

```
C:\github\test-win-path>php -f run.php
executable found by new PhpExecutableFinder()->find(false)
C:\tools\php82\php.exe

executable found by new PhpExecutableFinder()->find(true)
C:\tools\php82\php.exe
```

**Review by keradus — APPROVED** [review]

File: composer.json (hunk 2 above)
Comment (keradus) [inline composer.json:45]: if someone would install 7.0, would test still pass?
if not, I suggest to bump requirement to ^7.2

(no big value for having different test case depends on dependency version)

Comment (mvorisek) [reply composer.json:45]: That is a small issue, as it would weaken `--prefer-lowest` tests in dependant packages.

Comment (keradus) [reply composer.json:45]: I prefer those packages to stay with v3.66 and upgrade when they are ready to upgrade symfony/*, or to switch to shim version - over developer of Fixer having tests pasting or not depending on deps resolution

Comment (kubawerlos) [reply composer.json:45]: So, (put your own number here) developers using Unix systems will have to upgrade Symfony or not to upgrade PHP CS Fixer because of... Windows?

I imagine - as Symfony 7.0/7.1 are quite fresh - this could block quite a few people, and currently, there is no practical gain of blocking Symfony 7.0/7.1. If there will be a need to act, I'd go in the direction, where in the test we check if the command is `'php -l foo.php'` or `'c:\tools\php\php.EXE -l foo.php'`.

Comment (keradus) [reply composer.json:45]: if you want to do that extra check, go ahead.
but I don't believe we need to hyperfocus on those who can upgrade one library but cannot upgrade the 2nd. as especially for that (put your own number) fractal of users, we recommend to install shim

**Comment by keradus** [comment]
thanks @kubawerlos
