### PR TITLE
bug: Fix names resolving in `no_superfluous_phpdoc_tags` fixer

### LINKED ISSUE #5474: `no_superfluous_phpdoc_tags` does not work with NS for all cases
## Bug report

`@param` in code snippet below is not removed/fixed.

### Code snippet that reproduces the problem

```php
<?php

namespace Xxx\Xml;

class Writer
{
    /**
     * @param \Xxx\Xml\Node $rootNode
     *
     * @return string
     */
    public static function makeXml(Node $rootNode)
    {
    }
}
```

Expected output:
```php
<?php

namespace Xxx\Xml;

class Writer
 {
    /**
     * @return string
     */
    public static function makeXml(Node $rootNode)
    {
    }
}
```

Config:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in([__DIR__])
    ->exclude([
        'vendor',
    ]);

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@PhpCsFixer' => true,
        '@Symfony:risky' => true,
        '@PHP71Migration:risky' => true,
        '@PHP73Migration' => true,

        // required by PSR-12
        'concat_space' => [
            'spacing' => 'one',
        ],

        // disable some too strict rules
        'phpdoc_types_order' => [
            'null_adjustment' => 'always_last',
            'sort_algorithm' => 'none',
        ],
        'single_line_throw' => false,
        'yoda_style' => [
            'equal' => false,
            'identical' => false,
        ],
        'native_function_invocation' => false,
        'void_return' => false,
        'blank_line_before_statement' => [
            'statements' => ['break', 'continue', 'declare', 'return', 'throw', 'exit'],
        ],
        'combine_consecutive_issets' => false,
        'combine_consecutive_unsets' => false,
        'multiline_whitespace_before_semicolons' => false,
        'no_superfluous_elseif' => false,
        'ordered_class_elements' => false,
        'php_unit_internal_class' => false,
        'php_unit_test_class_requires_covers' => false,
        'phpdoc_add_missing_param_annotation' => false,
        'return_assignment' => false,
        'comment_to_phpdoc' => false,
        'list_syntax' => ['syntax' => 'short'],
        'general_phpdoc_annotation_remove' => [
            'annotations' => ['author', 'copyright', 'throws'],
        ],
        'nullable_type_declaration_for_default_null_value' => [
            'use_nullable_type_declaration' => false,
        ],
    ])
    ->setFinder($finder);
```

### PR DESCRIPTION
**Pull request by mvorisek**
fix #5474

- leading `\` always implies a FQCN
- CN /wo leading `\` must be resolved using `use`s and NS, for both native and phpdoc types
- `null` in native type implies `null` in phpdoc type - https://phpstan.org/r/7932c1fd-1bdb-4cf9-a18d-15b474a37ee6

### CODE REVIEW

**Comment by mvorisek** [comment]
@Wirone can you have a look on this PR?

File: src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php [hunk 1]
```diff
@@ -158,10 +159,16 @@ protected function applyFix(\SplFileInfo $file, Tokens $tokens): void
                 $content = $this->removeSuperfluousInheritDoc($content);
             }
 
+            $namespaceAnalysis = (new NamespacesAnalyzer())->getNamespaceAt($tokens, $index);
+            $namespace = $namespaceAnalysis->getFullName();
```
Comment (Wirone) [inline src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php:163]: `$namespaceAnalysis` is used once, so maybe there's no need to create variable.

```suggestion
            $namespace = (new NamespacesAnalyzer())->getNamespaceAt($tokens, $index)->getFullName();
```

Also I would prefer to add `?: null` and get rid of `if` below, but PHPStan's `DisallowedShortTernaryRule` strict rule would complain 😕. I am not a fan of this rule (side note).

File: src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php [hunk 2]
```diff
@@ -545,7 +558,18 @@ private function annotationIsSuperfluous(
...
+        if ($annotationTypes === $actualTypes) {
+            return true;
+        }
+
+        // retry comparison with annotation type unioned with null
+        // phpstan implies the null presence from the native type
+        $annotationTypes[] = 'null';
+        $annotationTypes = $this->toComparableNames($annotationTypes, null, null, []);
+
+        return $annotationTypes === $actualTypes;
```
Comment (Wirone) [inline src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php:572]: Personally I would squash it into, but it's only cosmetics.

```suggestion
        return $actualTypes === $this->toComparableNames(array_merge($annotationTypes, ['null']), null, null, []);
```

**Review by Wirone — APPROVED** [review]
Looks OK, there are 2 small refactorings I would like to see, but it's a bit subjective so it's non-blocking.

File: src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php (hunk 1 above)
Comment (mvorisek) [reply src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php:163]: `?:` is really not good as non-strict comparison is used, NS (PHP identifier in general) cannot start with `0`, thus it seems fine here, but I agree with phpstan and it should be not used nowhere...

Thus I am leaving this code as is, but I would not object any CS change before/after merge as I am not maintainer :)

Comment (Wirone) [reply src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php:163]: But the point of this comment was removing intermediary `$namespaceAnalysis` which is used only once (so superfluous for me), I mentioned `?:` only as a side note 😉.

Comment (mvorisek) [reply src/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixer.php]: Well I read it, but not sure if the complex one liners are more readable... But I landed it so this PR has zero feedback left :)
